"""Render a generated program as an sjasmplus source file.

One file per variant, self-contained, so a project can ``INCLUDE`` exactly
the variants it uses.  Patch points get local labels so the position
patcher can refer to them symbolically (``.p7+1`` is the immediate byte of
the instruction labelled ``.p7``) instead of by hard-coded address.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass

from ..ir import Program
from ..z80 import isa

INDENT = " " * 16


@dataclass
class ModuleInfo:
    """Everything the file header and metadata EQUs need."""

    name: str
    routine: str
    width: int
    height: int
    cells: int
    phase: int
    parity: int | None = None
    form: str = "single"
    reloc: str = "none"
    clip: str = "none"
    command_line: str = ""
    source: str = ""
    source_hash: str = ""
    palette: list[tuple[int, int, int]] | None = None
    lower_bound: int | None = None

    @property
    def label(self) -> str:
        """Fully qualified label stem, e.g. ``spr_ship_draw_xe``."""
        bits = [self.name, self.routine, self.form, "xo" if self.phase else "xe"]
        if self.parity is not None:
            bits.append("yo" if self.parity else "ye")
        return "_".join(bits)


def render(program: Program, info: ModuleInfo) -> str:
    """Produce the text of one sjasmplus module."""
    lines: list[str] = []
    add = lines.append

    add(";" + "-" * 71)
    add(f"; {info.label}")
    add(";")
    for line in textwrap.wrap(
        f"Compiled sprite for SAM Coupe mode 4: {info.width}x{info.height} pixels, "
        f"{info.cells} screen bytes touched, x phase {info.phase}"
        + (f", y parity {info.parity}" if info.parity is not None else "")
        + f", form {info.form}, relocation {info.reloc}, clipping {info.clip}.",
        72,
    ):
        add(f"; {line}")
    add(";")
    add(f"; Cost   : {program.tstates}T (nominal Z80 timing)")
    add(f"; Size   : {program.size} bytes")
    if program.patch_count:
        add(f"; Patches: {program.patch_count}")
    if info.lower_bound is not None and info.lower_bound > 0:
        gap = 100.0 * (program.tstates - info.lower_bound) / info.lower_bound
        add(f"; Bound  : {info.lower_bound}T lower bound ({gap:+.1f}%)")
    if info.source:
        add(f"; Source : {info.source}" + (f" ({info.source_hash})" if info.source_hash else ""))
    if info.command_line:
        for line in textwrap.wrap(f"Command: {info.command_line}", 72):
            add(f"; {line}")
    add("; Generated by codesprite - do not edit by hand.")
    add(";" + "-" * 71)
    add("")

    if info.palette:
        add(f"{info.label}_palette_rgb:")
        for index, (r, g, b) in enumerate(info.palette):
            add(f"{INDENT}DEFB {r},{g},{b}{' ' * 8}; index {index}")
        add("")

    add(f"{info.label}:")
    patch_index = 0
    for op, origin in zip(program.ops, program.origins):
        if isinstance(op, isa.Comment):
            add(f"{INDENT}{op.text()}")
            continue
        if isinstance(op, isa.Label):
            add(f"{op.name}:")
            continue
        prefix = ""
        if op.patches:
            prefix = f".p{patch_index}"
            patch_index += 1
        comment = ""
        if origin is not None:
            comment = f"; ({origin[0]},{origin[1]})"
        body = f"{op.text():<24}{comment}".rstrip()
        if prefix:
            add(f"{prefix}:")
        add(f"{INDENT}{body}")
    add(f"{INDENT}RET")
    add("")

    add(f"{info.label}_w{' ' * 8}EQU {info.width}")
    add(f"{info.label}_h{' ' * 8}EQU {info.height}")
    add(f"{info.label}_bytes{' ' * 4}EQU {info.cells}")
    add(f"{info.label}_tstates  EQU {program.tstates}")
    add(f"{info.label}_size{' ' * 5}EQU {program.size}")
    add(f"{info.label}_patches  EQU {program.patch_count}")
    add("")
    return "\n".join(lines)
