#!/usr/bin/env python3
"""Generate ballsdata.z80s from tests/balls.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import balls as B

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(b) for b in v[i:i + per])
                     for i in range(0, len(v), per))


def main():
    co = []
    for x, y, z in B.POINTS:
        co += [(x // B.S) & 0xFF, (y // B.S) & 0xFF, (z // B.S) & 0xFF]
    rows = []
    for off, ln in B.ROWS:
        rows += [off, ln]
    shade = [B.SHADE[min(3, (z - B.ZMIN) >> 5)] * 0x11 if z >= B.ZMIN
             else B.SHADE[0] * 0x11 for z in range(256)]

    p = os.path.join(ROOT, "ballsdata.z80s")
    open(p, "w").write("""\
;------------------------------------------------------------------
; Generated by tests/mkballsdata.py - do not edit.
;------------------------------------------------------------------

BL_N:           EQU %d      ; balls
BL_S:           EQU %d      ; half the cube they sit on
BL_TZ:          EQU %d     ; and how far away it is
BL_ZMIN:        EQU %d      ; the reciprocal table's floor
BL_BH:          EQU %d       ; rows in a ball

bl_da:          ; turns an axis per 256 frames
%s

bl_coord:       ; each ball's corner, as -1, 0 or 1 an axis
%s

bl_rows:        ; a ball, as (offset, length) a row of whole bytes
%s

        ALIGN 256
bl_recip:       ; 256*64/z
%s

        ALIGN 256
bl_shade:       ; z -> its shade, in both nibbles
%s
""" % (B.NBALLS, B.S, B.TZ, B.ZMIN, B.BH,
       defb(list(B.SPIN)), defb(co, 12), defb(rows),
       defb(B.RECIP), defb(shade)))
    print("wrote %s: %d balls" % (p, B.NBALLS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
