#!/usr/bin/env python3
"""Generate the tables chequer4.z80s reads.

    python3 tests/mkchq4data.py

chequer4 draws the same board as chequer3 out of the same compiled runs
- byte for byte the same bank, chequer3run.z80s and chequer3runlo.z80s,
including its entry tables - because moving the depth alternation out of
the palette and into the pixels does not change a single PUSH. What it
changes is what those PUSHes push.

So the only table that grows is the value sets: a scanline whose depth
parity is odd wants the two colours the other way round, which is every
byte of the set XOR 0x33, and that complement sits sixteen bytes above
the set itself. The row loop picks between them with one AND and one
ADD, from a mask byte a scanline that is 0x00 or 0x33 - the same byte
that turns the row's last byte round.

    chequer4data.z80s   the bands, the records, the value sets and
                        their complements, and the viewport
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chequer3 as C
import mkchq3data as M3
from mkhrdata import fog

C1 = 0x1111                     # the two colour indices, both nibbles
C2 = 0x2222
SWAP = 0x33                     # what exchanges them, one byte


def main(here):
    vtab, vidx, rec = [], {}, []
    for p in C.WIDTHS:
        for t in (0, 1):
            _, _, vals = M3.build(p, t)
            v = ((C1 & 255, C1 >> 8), (C2 & 255, C2 >> 8))
            v = tuple(x[j] for x in v for j in (0, 1)) \
                + tuple(vals[i][j] for i in (0, 2, 3, 1) for j in (0, 1))
            if v not in vidx:
                vidx[v] = len(vtab)
                vtab.append(v)
            rec.append(("chq3_e%d_%d" % (p, t),
                        "chq4_val + %d" % (32 * vidx[v])))

    band, y = [], C.H - 1
    while y >= C.TOP:
        p = C.PTAB[y]
        n = 0
        while y >= C.TOP and C.PTAB[y] == p:
            n += 1
            y -= 1
        band.append((n, p))
    assert [p for _, p in band] == list(range(C.WIDTHS[-1],
                                              C.WIDTHS[0] - 1, -1))
    spill = C.kmax(C.PTAB[C.TOP])

    val = []
    for v in vtab:
        val.append("        DEFB " + ",".join(str(x) for x in v))
        val.append("        DEFS 4")
        val.append("        DEFB " + ",".join(str(x ^ SWAP) for x in v))
        val.append("        DEFS 4")

    fg, hz = fog()
    parts = ["; Generated by tests/mkchq4data.py - do not edit by hand.",
             "; The runs and their entry tables are chequer3's, unchanged.",
             "\nCHQ4_HZ:        EQU %d" % C.HZ,
             "CHQ4_TOP:       EQU %d          ; first row with a board" % C.TOP,
             "CHQ4_HAZE:      EQU %d          ; and what is above it"
             % (C.HAZE * 0x11),
             "CHQ4_SWAP:      EQU %d          ; exchanges the two colours"
             % SWAP,
             "CHQ4_SPILL:     EQU %d           ; PUSHes the topmost run can"
             % (spill + 1),
             "                                ; overrun the row above by",
             "\nchq4_band:      ; rows, and the pair of records, widest",
             "                ; square first",
             "\n".join("        DEFB %d\n        DEFW chq4_rec + %d,"
                       "chq4_rec + %d"
                       % (n, 8 * (p - C.WIDTHS[0]), 8 * (p - C.WIDTHS[0]) + 4)
                       for n, p in band),
             "        DEFB 0",
             "\nchq4_rec:       ; a run's entry points and its values",
             "\n".join("        DEFW %s,%s" % (o, v) for o, v in rec),
             "\n        ALIGN 32",
             "chq4_val:       ; BC, DE, HL, IX, IY and AF in the order a row",
             "                ; POPs them, and sixteen bytes on, the same set",
             "                ; with the two colours exchanged",
             "\n".join(val),
             "\n        ALIGN 256\nchq4_ztab:\n" + M3.defw(C.ZTAB),
             "\n        ALIGN 256\nchq4_fog:\n" + M3.defb(fg),
             "\nchq4_hazec:\n" + M3.defb(hz)]
    open(os.path.join(here, "chequer4data.z80s"), "w").write(
        "\n".join(parts) + "\n")

    print("%d value sets and their complements, %d bytes; %d bands, "
          "%d bytes of record"
          % (len(vtab), 32 * len(vtab), len(band), 4 * len(rec)))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
