#!/usr/bin/env python3
"""Generate chequerdata.z80s: the tables chequer.z80s reads.

    python3 tests/mkchqdata.py

All of it is fixed by the camera height, which does not change, so none
of it is built on the Z80: the depth of each scanline, how wide a square
is there, and the two colours the palette gives that scanline.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chequer as C


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def defw(v, per=8):
    return "\n".join("        DEFW " + ",".join(str(x & 0xFFFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def fog():
    """The two SAM colours a scanline gets, near to far.

    Green board fading blue with distance; the sky is the same two
    entries, so it grades as well without costing a thing.
    """
    def mix(a, b, t):
        return [x + (y - x) * t for x, y in zip(a, b)]

    out = []
    for y in range(C.H):
        if y <= C.HZ:                       # sky, deep overhead and pale
            t = y / C.HZ                    # at the horizon
            out += [sam(*mix((0, 1, 5), (2, 4, 7), t)), sam(0, 0, 0)]
        else:                               # and the board fading into it
            t = (y - C.HZ) / (C.H - C.HZ)
            out += [sam(*mix((1, 4, 5), (0, 7, 2), t)),
                    sam(*mix((0, 3, 4), (0, 3, 1), t))]
    return out


def sam(r, g, b):
    """A SAM palette byte, 0..127.

    Two bits a gun and a bright bit the three of them share, packed
    G1 R1 B1 BR G0 R0 B0. That layout wants confirming against the
    hardware manual before any of this runs on a real machine; nothing
    here depends on it being right except the colours in the GIF, which
    tests/mkgif.py unpacks the same way.
    """
    r, g, b = [max(0, min(7, int(round(v)))) for v in (r, g, b)]
    br = 1 if ((r & 1) + (g & 1) + (b & 1)) >= 2 else 0
    v = br << 3
    for hi, lo, c in ((6, 2, g), (5, 1, r), (4, 0, b)):
        v |= ((c >> 2) & 1) << hi
        v |= ((c >> 1) & 1) << lo
    return v


def main(path):
    idx = [0] * C.H                     # which run a scanline uses
    for y in range(C.H):
        if C.PTAB[y]:
            idx[y] = C.PERIODS.index(C.PTAB[y]) + 1
    # where a run is entered with the camera at zero, and the cycle it
    # wraps in: the frame's own offset is one subtract off this
    kt = [0, 0]                         # a pair a period, so one pointer
    for p in C.PERIODS:
        kt += [(p // 4 - 32) % (p // 2), p // 2]
    top = min(y for y in range(C.H) if idx[y])
    band = []                           # rows sharing a run, bottom first
    y = C.H - 1
    while y >= top:
        n = 0
        while y - n >= top and idx[y - n] == idx[y]:
            n += 1
        band += [n, idx[y]]
        y -= n
    band += [0, 0]
    parts = ["; Generated by tests/mkchqdata.py - do not edit by hand.",
             "\nCHQ_HZ:         EQU %d" % C.HZ,
             "CHQ_NP:         EQU %d" % len(C.PERIODS),
             "CHQ_TOP:        EQU %d          ; first scanline with a board"
             % top,
             "CHQ_SPILL:      EQU %d           ; PUSHes the topmost run can"
             "\n                                ; overrun the row above by"
             % (2 * idx[top]),
             "\n        ALIGN 256\nchq_ptab:\n" + defb(idx),
             "\n        ALIGN 256\nchq_ztab:\n" + defw(C.ZTAB),
             "\n        ALIGN 256\nchq_fog:\n" + defb(fog()),
             "\nchq_kt:\n" + defb(kt),
             "\nchq_band:\n" + defb(band)]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: %d periods %s, board from row %d, %d bands"
          % (path, len(C.PERIODS), C.PERIODS[:3] + ["..."] + C.PERIODS[-1:],
             top, len(band) // 2 - 1))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "chequerdata.z80s"))
