#!/usr/bin/env python3
"""Generate the tables chequer4.z80s reads.

    python3 tests/mkchq4data.py

chequer4 draws the same board as chequer3 out of the same compiled runs
- byte for byte the same bank, chequer3run.z80s and chequer3runlo.z80s,
including its entry tables - because moving the depth alternation out of
the palette and into the pixels does not change a single PUSH. What it
changes is what those PUSHes push.

So the only table that grows is the value sets: a scanline whose depth
parity is odd wants the two colours the other way round, which is every
byte of the set XOR 0x33, and that complement sits sixteen bytes above
the set itself. The row loop picks between them with one AND and one
ADD, from a mask byte a scanline that is 0x00 or 0x33 - the same byte
that turns the row's last byte round.

    chequer4data.z80s   the bands, the records, the value sets and
                        their complements, and the viewport
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chequer3 as C
import mkchq3data as M3

FULL = C.PTAB[C.TOP] == 1       # the board goes all the way to the horizon
PRE = M3.PRE                    # which run bank the records point into
SET = os.environ.get("CHQ_SET", "5" if FULL else "4")   # whose tables
OUT = "chequer%sdata.z80s" % SET                        # these are: a
MSK = "chequer%smsk%%d.z80s" % SET                      # demo with a
EQU = "chequer%sequ.z80s" % SET                         # viewport of
                                                        # its own has a
                                                        # set of its own
C1 = 0x1111                     # the two colour indices, both nibbles
C2 = 0x2222
SWAP = 0x33                     # what exchanges them, one byte
SKY = int(os.environ.get("HARRIER_SKY", 1))     # and the sky: the board's
                                # own first colour where a copper grades
                                # the two apart by scanline, and an index
                                # of its own where the palette has to sit
                                # still, because then one index cannot be
                                # both the sky and the near squares


def masks(here):
    """The swap mask a scanline, for every depth it can have.

    chq4_msk8 worked this out every frame: 81 T-states a scanline to add
    camz to the row's depth and keep bit 8 of it, which is 7,807 for a
    95 row board. But bit 8 of (ztab[y] + camz) does not change when camz
    changes by 512, and it inverts when camz changes by 256 - so the
    whole table is a function of camz mod 512, and there are only 512 of
    them. At a 128 byte stride that is 64K, which is two pages of a SAM
    and nothing at all in a machine with sixteen.

    The camera's own square is a parity too, and it goes in the same
    index: adding 256 to camz is exactly what it does.
    """
    rows = C.H - C.TOP
    for chunk in (0, 1):
        parts = ["; Generated by tests/mkchq4data.py - do not edit by hand.",
                 "; The swap mask a scanline, for depths %d to %d mod 512:"
                 % (256 * chunk, 256 * chunk + 255),
                 "; %d rows a table, on a 128 byte stride so that the index"
                 % rows,
                 "; is a shift.",
                 "\n        ORG 0x0000"]
        for lo in range(256):
            i = 256 * chunk + lo
            m = [SWAP if ((C.ZTAB[y] + i) >> 8) & 1 else 0
                 for y in range(C.TOP, C.H)]
            parts.append(M3.defb(m, 16))
            parts.append("        DEFS %d" % (128 - rows))
        open(os.path.join(here, MSK % chunk), "w").write(
            "\n".join(parts) + "\n")
    print("%s: 512 tables of %d rows, 64K in two chunks"
          % (MSK % 0, rows))


def values():
    """The value sets a run POPs, and which set each (width, way round)
    wants - shared out, because most runs want the same few."""
    vtab, vidx, which = [], {}, {}
    for p in C.WIDTHS:
        for t in (0, 1):
            _, _, vals = M3.build(p, t)
            v = ((C1 & 255, C1 >> 8), (C2 & 255, C2 >> 8))
            v = tuple(x[j] for x in v for j in (0, 1)) \
                + tuple(vals[i][j] for i in (0, 2, 3, 1) for j in (0, 1))
            if v not in vidx:
                vidx[v] = len(vtab)
                vtab.append(v)
            which[(p, t)] = vidx[v]
    return vtab, which


def bands():
    """The rows each width covers, widest square first."""
    band, y = [], C.H - 1
    while y >= C.TOP:
        p = C.PTAB[y]
        n = 0
        while y >= C.TOP and C.PTAB[y] == p:
            n += 1
            y -= 1
        band.append((n, p))
    return band


def main(here):
    vtab, which = values()
    rec = []
    for p in C.WIDTHS:
        for t in (0, 1):
            rec.append(("%s_e%d_%d" % (PRE, p, t),
                        "chq4_val + %d" % (32 * which[(p, t)])))

    band = bands()
    assert [p for _, p in band] == list(range(C.WIDTHS[-1],
                                              C.WIDTHS[0] - 1, -1))
    spill = C.kmax(C.PTAB[C.TOP])

    val = []
    for v in vtab:
        val.append("        DEFB " + ",".join(str(x) for x in v))
        val.append("        DEFS 4")
        val.append("        DEFB " + ",".join(str(x ^ SWAP) for x in v))
        val.append("        DEFS 4")

    equ = ["; Generated by tests/mkchq4data.py - do not edit by hand.",
           "; The viewport, which the code and the bank both need to know.",
           "\nCHQ4_HZ:        EQU %d" % C.HZ,
             "CHQ4_TOP:       EQU %d          ; first row with a board" % C.TOP,
             "CHQ4_HAZE:      EQU %d          ; and what is above it"
             % (C.HAZE * 0x11),
             "CHQ4_SWAP:      EQU %d          ; exchanges the two colours"
             % SWAP,
             "CHQ4_ABOVE:     EQU %d          ; and what the top run spills"
             % (C.HAZE * 0x11 if C.TOP > C.HZ + 1 else SKY * 0x11,
                ),
             "                                ; into, haze or sky",
             "CHQ4_SKYC:      EQU 0x%04X      ; the sky, both nibbles of"
             % (SKY * 0x1111),
             "                                ; both bytes",
           "CHQ4_SPILL:     EQU %d           ; PUSHes the topmost run can"
           % (spill + 1),
           "                                ; overrun the row above by"]
    open(os.path.join(here, EQU), "w").write("\n".join(equ) + "\n")

    parts = ["; Generated by tests/mkchq4data.py - do not edit by hand.",
             "; The runs and their entry tables are %s's, unchanged."
             % ("chequer5's own bank" if FULL else "chequer3"),
             "\nchq4_band:      ; rows, and the pair of records, widest",
             "                ; square first",
             "\n".join("        DEFB %d\n        DEFW chq4_rec + %d,"
                       "chq4_rec + %d"
                       % (n, 8 * (p - C.WIDTHS[0]), 8 * (p - C.WIDTHS[0]) + 4)
                       for n, p in band),
             "        DEFB 0",
             "\nchq4_rec:       ; a run's entry points and its values",
             "\n".join("        DEFW %s,%s" % (o, v) for o, v in rec),
             "\n        ALIGN 32",
             "chq4_val:       ; BC, DE, HL, IX, IY and AF in the order a row",
             "                ; POPs them, and sixteen bytes on, the same set",
             "                ; with the two colours exchanged",
             "\n".join(val),
             "\nchq4_ztab:      ; the depth of each row with a board on it,",
             "                ; and nothing above that",
             M3.defw(C.ZTAB[C.TOP:])]
    open(os.path.join(here, OUT), "w").write("\n".join(parts) + "\n")

    masks(here)
    print("%s: %d value sets and their complements, %d bytes; %d bands, "
          "%d bytes of record, %d rows of board"
          % (OUT, len(vtab), 32 * len(vtab), len(band), 4 * len(rec),
             C.H - C.TOP))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
