#!/usr/bin/env python3
"""Generate the runs and tables chequer3.z80s reads.

    python3 tests/mkchq3data.py

One compiled run per square width per odd pixel of phase - the even
pixel is a byte, which the stack pointer can shift for nothing. A run
pushes one of six things: BC and DE are the two colours, and HL, AF,
IX and IY carry a boundary that lands inside a PUSH. An odd width
needs all four of those, because its boundaries walk through all four
offsets inside a PUSH; an even one needs two.

Three files, because the runs are nine kilobytes and the free memory
is in two pieces either side of the screen buffers:

    chequer3run.z80s    the runs that fit above the buffers
    chequer3runlo.z80s  and the rest, which go below them
    chequer3data.z80s   where each run starts, what it wants in its
                        registers, and the viewport
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chequer3 as C
from mkhrdata import fog

HIGH = 0xFE00 - 0xE000          # above the buffers, below the stack

# The runs depend on the viewport, so the full-depth board - the one that
# goes to the horizon rather than stopping at eight-pixel squares - gets a
# bank of its own. HARRIER_MINP picks which, and nothing else changes.
FULL = C.PTAB[C.TOP] == 1
PRE = "chq5" if FULL else "chq3"
SOLID = {(0x11, 0x11): "BC", (0x22, 0x22): "DE"}
BOUND = ["HL", "AF", "IX", "IY"]
OP = {"BC": [0xC5], "DE": [0xD5], "HL": [0xE5], "AF": [0xF5],
      "IX": [0xDD, 0xE5], "IY": [0xFD, 0xE5]}
EDGE = [0x11, 0x12, 0x21, 0x22]


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def defw(v, per=8):
    return "\n".join("        DEFW " + ",".join(str(x & 0xFFFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def words(p, t):
    """The run as the words it pushes, low address byte first."""
    return [((px[0] << 4) | px[1], (px[2] << 4) | px[3])
            for px in C.pattern(p, t)]


def build(p, t):
    """One run: its opcodes, what it wants in its four spare pairs,
    and where each entry point sits inside it."""
    w = words(p, t)
    n = {}
    for x in w:
        if x not in SOLID:
            n[x] = n.get(x, 0) + 1
    order = sorted(n, key=lambda x: (-n[x], x))
    assert len(order) <= 4, (p, t, order)        # four spare pairs, no more
    reg = dict(SOLID)
    for i, x in enumerate(order):
        reg[x] = BOUND[i]
    ops = [OP[reg[x]] for x in w]

    ent, at = [], 0
    for k in range(C.kmax(p)):
        # the row's last byte, which a shifted run does not reach, is
        # the left hand half of the PUSH before the one it enters at
        ent.append((at, w[k - 1][0] if k else words(p, t + 4)[0][0]))
        at += len(ops[k])
    vals = [order[i] if i < len(order) else (0, 0) for i in range(4)]
    return ops, ent, vals


def main(here):
    runs, size = [], 0
    for p in C.WIDTHS:
        for t in (0, 1):
            ops, ent, vals = build(p, t)
            b = sum(len(o) for o in ops) + 3     # and the JP out of it
            runs.append((p, t, ops, ent, vals, b))
            size += b

    # the entry tables go above the buffers with the runs, and take
    # their room first: three bytes for each whole PUSH of phase, which
    # is an address to jump to and the row's last byte to store
    etab = []
    for p, t, _, ent, _, _ in runs:
        etab.append("%s_e%d_%d:" % (PRE, p, t))
        for g in range(C.kmax(p)):
            at, edge = ent[C.kmax(p) - 1 - g]
            etab.append("        DEFB (%s_r%d_%d + %d) & 255, "
                        "(%s_r%d_%d + %d) >> 8, %d"
                        % (PRE, p, t, at, PRE, p, t, at, edge))
    esize = 3 * sum(C.kmax(p) for p in C.WIDTHS) * 2

    # the runs, as much as fits above the screen buffers and the rest
    # below them; nothing outside this file cares which is which
    hi, lo, at = [], [], esize
    for r in runs:
        (hi if at + r[5] <= HIGH else lo).append(r)
        if at + r[5] <= HIGH:
            at += r[5]
    for name, part, path in (("above", hi, "chequer%srun.z80s"
                              % ("5" if FULL else "3")),
                             ("below", lo, "chequer%srunlo.z80s"
                              % ("5" if FULL else "3"))):
        body = []
        for p, t, ops, _, _, _ in part:
            body.append("%s_r%d_%d:" % (PRE, p, t))
            body.append(defb([b for o in ops for b in o]))
            body.append("        JP %s_ret" % PRE)
        open(os.path.join(here, path), "w").write(
            "; Generated by tests/mkchq3data.py - do not edit by hand.\n"
            "; The runs that go %s the screen buffers.\n\n" % name
            + ("%s_ent:\n" % PRE + "\n".join(etab) + "\n\n"
               if part is hi else "")
            + "\n".join(body) + "\n")

    if FULL:                        # chequer4's generator makes the tables
        print("%d runs, %d bytes: %d above the buffers with %d of entries, "
              "%d below" % (len(runs), size, sum(r[5] for r in hi), esize,
                            sum(r[5] for r in lo)))
        return

    # one offset table a run, one value table between all the runs that
    # want the same four pairs, and one record a run pointing at both
    vtab, vidx, rec = [], {}, []
    for p, t, ops, ent, vals, _ in runs:
        v = tuple(vals[i][j] for i in (0, 2, 3, 1) for j in (0, 1))
        if v not in vidx:
            vidx[v] = len(vtab)
            vtab.append(v)
        rec.append(("chq3_e%d_%d" % (p, t), "chq3_val + %d" % (8 * vidx[v])))

    band, y = [], C.H - 1
    while y >= C.TOP:
        p = C.PTAB[y]
        n = 0
        while y >= C.TOP and C.PTAB[y] == p:
            n += 1
            y -= 1
        band.append((n, p))
    assert [p for _, p in band] == list(range(C.WIDTHS[-1],
                                              C.WIDTHS[0] - 1, -1))
    spill = C.kmax(C.PTAB[C.TOP])

    fg, hz = fog()
    parts = ["; Generated by tests/mkchq3data.py - do not edit by hand.",
             "\nCHQ3_HZ:        EQU %d" % C.HZ,
             "CHQ3_TOP:       EQU %d          ; first row with a board" % C.TOP,
             "CHQ3_HAZE:      EQU %d          ; and what is above it"
             % (C.HAZE * 0x11),
             "CHQ3_PMAX:      EQU %d          ; the bands run from this"
             % C.WIDTHS[-1],
             "CHQ3_SPILL:     EQU %d           ; PUSHes the topmost run can"
             % (spill + 1),
             "                                ; overrun the row above by",
             "\nchq3_band:      ; rows, and the pair of records, widest",
             "                ; square first",
             "\n".join("        DEFB %d\n        DEFW chq3_rec + %d,"
                       "chq3_rec + %d"
                       % (n, 8 * (p - C.WIDTHS[0]), 8 * (p - C.WIDTHS[0]) + 4)
                       for n, p in band),
             "        DEFB 0",
             "\nchq3_rec:       ; a run's entry points and its pairs",
             "\n".join("        DEFW %s,%s" % (o, v) for o, v in rec),
             "\nchq3_val:       ; HL, IX, IY and AF, in the order a row POPs",
             "\n".join(defb(list(v), 8) for v in vtab),

             "\n        ALIGN 256\nchq3_ztab:\n" + defw(C.ZTAB),
             "\n        ALIGN 256\nchq3_fog:\n" + defb(fg),
             "\nchq3_hazec:\n" + defb(hz)]
    open(os.path.join(here, "chequer3data.z80s"), "w").write(
        "\n".join(parts) + "\n")

    print("%d runs, %d bytes: %d above the buffers with %d of entries, "
          "%d below" % (len(runs), size, sum(r[5] for r in hi), esize,
                        sum(r[5] for r in lo)))
    print("tables: %d value sets, %d bands, %d bytes of record"
          % (len(vtab), len(band), 4 * len(rec)))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
