#!/usr/bin/env python3
"""Generate the runs and tables chequer2.z80s reads.

    python3 tests/mkchq2data.py

Four compiled runs per square width instead of chequer's one - t = 0,
1, 2 and 3 pixels of phase - so the board's phase is exact and a
scanline is still one dispatch. Where a boundary lands inside a PUSH
that PUSH carries a pair with a pixel of each colour, which is why a
run pushes one of four registers rather than one of two.

Two files, because the runs are 5K and live above the screen buffers:

    chequer2run.z80s   the runs themselves, at CHQ2_RUNS
    chequer2tab.z80s   where each starts, and the boundary pairs

The viewport tables - which square a scanline gets, the depths, the
colours - are chequer's and are shared with it.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chequer2 as C

PUSHOP = {"11": 0xC5, "22": 0xD5, "12": 0xE5, "21": 0xF5}


def kind(px):
    """Which register this PUSH wants: both colours, or a boundary."""
    if px[0] == px[1] == px[2] == px[3]:
        return "%d%d" % (px[0], px[0])
    return "%d%d" % (px[0], px[3])          # a boundary, and which way


def pair(px):
    """The two bytes it pushes: low address first."""
    return ((px[0] << 4) | px[1], (px[2] << 4) | px[3])


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(run_path, tab_path):
    runs, names, pairs = [], [], {}
    for p in C.PERIODS:
        i = p // 4
        for t in range(4):
            pat = C.pattern(p, t)
            ops = []
            for px in pat:
                k = kind(px)
                ops.append(PUSHOP[k])
                if k in ("12", "21"):
                    # every boundary in a run is at the same offset, so
                    # one pair value each way round serves the whole of it
                    was = pairs.setdefault((t, k), pair(px))
                    assert was == pair(px), (p, t, k)
            names.append("chq2_r%d_%d" % (i, t))
            runs.append(ops)
    body = []
    for n, ops in zip(names, runs):
        body.append("%s:" % n)
        body.append(defb(ops))
        body.append("        JP (IY)")
    open(run_path, "w").write(
        "; Generated by tests/mkchq2data.py - do not edit by hand.\n"
        "; The runs. Assemble at CHQ2_RUNS, above the screen buffers.\n\n"
        + "\n".join(body) + "\n")

    vals = []
    for t in range(4):
        for k in ("12", "21"):
            lo, hi = pairs.get((t, k), (0, 0))
            vals += [lo, hi]
    tab = ["; Generated by tests/mkchq2data.py - do not edit by hand.",
           "\nCHQ2_NRUN:      EQU %d" % len(names),
           "\nchq2_base:      ; where each run starts, by (square, phase)"]
    for i in range(0, len(names), 4):
        tab.append("        DEFW " + ",".join(names[i:i + 4]))
    tab.append("\nchq2_pair:      ; the boundary pairs: 1-to-2 then 2-to-1,")
    tab.append("                ; a pair of them for each phase")
    tab.append(defb(vals, 8))
    open(tab_path, "w").write("\n".join(tab) + "\n")
    print("wrote %s: %d runs, %d bytes\nwrote %s: %d addresses, 8 pairs"
          % (run_path, len(names), sum(len(o) + 2 for o in runs), tab_path,
             len(names)))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "chequer2run.z80s"),
         os.path.join(here, "chequer2tab.z80s"))
