#!/usr/bin/env python3
"""Generate citydata.z80s: the two skylines chequer7 scrolls.

    python3 tests/mkcitydata.py

A building is eight bytes, four of which the Z80 could work out and
should not have to: where it starts in its layer, how wide it is, how
many scanlines tall, where to enter the fill block for that width, the
address its top row ends at when the layer's offset is zero, and where
its top row is. The first three are the building; the rest are what the
setup would otherwise cost, and the setup was costing as much as the
pixels did.

The layers' period is the screen's width, so a layer is one copy of
itself and the offset is a mask. The last building of a layer runs past
the period's end and wraps; the code has to cut a building at the
screen's edge in any case.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import city as C                                        # noqa: E402


def table(name, blds, what):
    out = ["\n%s:      ; %s" % (name, what),
           "                ; x, width, rows, where to enter the fill",
           "                ; block, where its top row ends at offset",
           "                ; zero, and where its top row is"]
    for x, w, h in blds:
        top = (C.ROWS - h) * C.STRIDE
        out.append("        DEFB %3d,%2d,%2d,%2d\n"
                   "        DEFW C7_BASE + %d + %d, %d"
                   % (x, w, h, 64 - w // 2, top, w, top))
    out.append("        DEFB 255        ; and the end of the layer")
    return "\n".join(out)


def main(here):
    pair = lambda i: 0x1111 * i                        # noqa: E731
    parts = [
        "; Generated by tests/mkcitydata.py - do not edit by hand.",
        "; The city on the horizon: two layers of buildings and the band",
        "; they live in. See tests/city.py.",
        "\nC7_TOP:         EQU %d          ; the band's first scanline"
        % C.TOP,
        "C7_ROWS:        EQU %d          ; and how many of them" % C.ROWS,
        "C7_SKY:         EQU 0x%04X      ; the board's own sky, as a pair"
        % pair(C.SKY),
        "C7_FAR:         EQU 0x%04X      ; the far layer, flat" % pair(C.FAR),
        "C7_NEAR:        EQU 0x%04X      ; the near one, darker"
        % pair(C.NEAR),
        "C7_LIT:         EQU 0x%04X      ; and its left face" % pair(C.LIT),
        table("c7_fars", C.FARS, "the far layer, one byte a frame"),
        table("c7_nears", C.NEARS, "and the near one, two")]
    open(os.path.join(here, "citydata.z80s"), "w").write(
        "\n".join(parts) + "\n")
    n = len(C.FARS) + len(C.NEARS)
    push = sum(w for _, w, h in C.FARS + C.NEARS for _ in range(h)) // 2
    print("citydata.z80s: %d buildings in %d bytes; %d pairs a frame of "
          "building over %d of sky"
          % (n, 8 * n + 2, push, C.ROWS * C.STRIDE // 2))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
