#!/usr/bin/env python3
"""Generate cubesdata.z80s: the room, the walls and the cubes.

    python3 tests/mkcubesdata.py

All of it comes out of tests/cubes.py, which is the model the Z80 is
checked against, so the two cannot drift apart.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cubes as C


def defb(v, per=12):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF) for x in v[i:i + per])
                     for i in range(0, len(v), per))


def word(v):
    return [v & 0xFF, (v >> 8) & 0xFF]


def main(path):
    corners, front, inner = C.edges()
    (lx, ty), (rx, by) = front
    st = []
    for cu in C.cubes_start():
        st += cu[3]                     # dax, day, daz
        st += cu[2]                     # ax, ay, az
        for i in range(3):
            st += word(cu[0][i]) + word(cu[1][i]) + [0]
        st += [0] * (24 - 21)
    parts = [
        "; Generated by tests/mkcubesdata.py - do not edit by hand.",
        "\nCB_N:           EQU %d           ; cubes" % C.N,
        "CB_G:           EQU %d           ; gravity, velocity units a frame"
        % C.G,
        "CB_D:           EQU %d       ; how close two centres may come"
        % (2 * C.S * 128),
        "CB_ROOM:        EQU %d           ; the room's colour" % C.ROOM,
        "CB_TOP:         EQU %d           ; the viewport, which is the room's"
        % ty,
        "CB_BOT:         EQU %d          ; front face seen end on" % by,
        "CB_LX:          EQU %d           ; and the columns its sides are on"
        % lx,
        "CB_RX:          EQU %d         " % rx,
        "\ncb_lim:         ; each axis: the high wall, then the low one",
        "\n".join("        DEFW %d,%d" % (hi, lo)
                  for hi, lo in ((C.XLIM, -C.XLIM), (C.YLIM, -C.YLIM),
                                 (C.ZMAX, C.ZMIN))),
        "\ncb_edges:       ; the eight edges a cube can get in front of",
        "\n".join("        DEFB %d,%d,%d,%d"
                  % (corners[a][0], corners[a][1], corners[b][0],
                     corners[b][1]) for a, b in inner),
        "\ncb_pal:         ; the ramp each face of each cube starts at",
        "\n".join(defb(C.BASE[i % len(C.BASE)], 6) for i in range(C.N)),
        "\ncb_start:       ; where they begin, and how fast they spin",
        defb(st, 12),
    ]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: %d cubes, room %d..%d by %d..%d, %d edges drawn a frame"
          % (path, C.N, lx, rx, ty, by, len(inner)))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "cubesdata.z80s"))
