#!/usr/bin/env python3
"""Generate ensembledata.z80s - the two voices' tables, packed for the
channel map ensemble.py describes.

    python3 tests/mkensembledata.py

The envelopes, the vibrato and the phrase come out of shakudata.z80s
and stringsdata.z80s unchanged - only the note and chord tables are
different here, because the octave nibbles land in different registers
when the two voices share the chip.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ensemble as E
import shaku as K
import strings as T

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    o = []
    w = o.append
    w(";------------------------------------------------------------------")
    w("; ensembledata.z80s - generated by tests/mkensembledata.py, do not edit")
    w(";")
    w("; The tables that change when the flute and the strings share the")
    w("; chip. Everything else - envelopes, vibrato, the phrase, the chord")
    w("; lengths - is shakudata.z80s's and stringsdata.z80s's.")
    w(";------------------------------------------------------------------")
    w("")
    w("EN_NOISEOCT:    EQU %d           ; the breath's octave, register 0x10"
      % E.NOISE_OCT)
    w("EN_SUS:         EQU %d           ; the pad, under the flute" % E.SUS)
    w("EN_INITS:       EQU %d          ; registers en_init sets up"
      % len(E.INIT))
    w("")
    w("; each flute note: frequency byte, its octave in the high nibble for")
    w("; register 0x10, and the octave above in the low nibble for 0x11")
    w("en_notes:")
    for i, (octave, n) in enumerate(K.NOTE):
        w("        DEFB %3d,0x%02X,0x%02X            ; %-3s %6.1f Hz"
          % (n, octave << 4, octave + 1, K.NAMES[i], K.hz(n, octave)))
    w("")
    w("; each chord: the root's byte and its octave for 0x11's high nibble,")
    w("; then the third and the fifth for 0x12's two nibbles, then frames")
    w("en_chords:")
    for (notes, dur), (names, _) in zip(T.CHORD, T.CHORDS):
        (n0, o0), (n1, o1), (n2, o2) = notes
        w("        DEFB %3d,0x%02X,%3d,0x%02X,%3d,0x%02X,%3d   ; %-12s %5.2f s"
          % (n0, (o0 & 7) << 4, n1, o1 & 7, n2, (o2 & 7) << 4, dur,
             "-".join(names), dur / 50.0))
    w("")
    w("en_ini:")
    for r, v in E.INIT:
        w("        DEFB 0x%02X,0x%02X" % (r, v))
    w("")
    path = os.path.join(ROOT, "ensembledata.z80s")
    open(path, "w").write("\n".join(o) + "\n")
    print("%s: %d notes, %d chords" % (path, len(K.NOTE), len(T.CHORD)))


if __name__ == "__main__":
    main()
