#!/usr/bin/env python3
"""Generate harrierdata.z80s: the tables harrier.z80s reads.

    python3 tests/mkhrdata.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import harrier as A
from mkchqdata import sam


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def defw(v, per=8):
    return "\n".join("        DEFW " + ",".join(str(x & 0xFFFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def rows():
    """Four bytes a scanline: p, B0, M, and K with the step flag.

    B0 is where the rightmost boundary sits with the camera at zero, M
    is 127 mod p and K the parity of 127 / p - between them they place
    the first boundary and say which colour the right hand edge is. The
    top bit of the last byte says p grew here, which is when the
    camera's offset needs stepping.
    """
    out = []
    prev = None
    for y in range(A.H):
        p = A.PTAB[y]
        if not p:
            out += [0, 0, 0, 0]
            continue
        # the flag says the square grew here, so the camera's offset
        # scales up with it. The first row drawn is where the offset is
        # worked out from scratch, so it must not also step.
        step = 0x80 if (prev is not None and p != prev) else 0
        out += [p, 128 + p * (127 // p), 127 % p, ((127 // p) & 1) | step]
        prev = p
    return out


def mixed():
    """A boundary lands mid-byte: the PUSH that straddles it.

    Four offsets for each way round. A PUSH writes its low register at
    the lower address, which is the left hand pair of pixels.
    """
    out = []
    for c, n in ((1, 2), (2, 1)):
        for t in range(4):
            px = [n if i < t else c for i in range(4)]
            out += [(px[0] << 4) | px[1], (px[2] << 4) | px[3]]
    return out


def fog():
    def mix(a, b, t):
        return [x + (y - x) * t for x, y in zip(a, b)]
    out, haze = [], []
    for y in range(A.H):
        if y <= A.HZ:
            t = y / A.HZ
            out += [sam(*mix((0, 1, 5), (2, 4, 7), t)), sam(0, 0, 0)]
            haze.append(sam(*mix((0, 1, 5), (2, 4, 7), t)))
        else:
            t = (y - A.HZ) / (A.H - A.HZ)
            lo = mix((1, 4, 5), (0, 7, 2), t)
            hi = mix((0, 3, 4), (0, 3, 1), t)
            out += [sam(*lo), sam(*hi)]
            haze.append(sam(*[(a + b) / 2 for a, b in zip(lo, hi)]))
    return out, haze


def main(path):
    fg, hz = fog()
    parts = ["; Generated by tests/mkhrdata.py - do not edit by hand.",
             "\nHR_HZ:          EQU %d" % A.HZ,
             "HR_TOP:         EQU %d          ; first row with a board" % A.TOP,
             "HR_HAZE:        EQU %d          ; and what is above it"
             % (A.HAZE * 0x11),
             "\n        ALIGN 256\nhr_mx:\n" + defb(mixed()),
             "\n        ALIGN 256\nhr_row:\n" + defb(rows(), 8),
             "\n        ALIGN 256\nhr_ztab:\n" + defw(A.ZTAB),
             "\n        ALIGN 256\nhr_fog:\n" + defb(fg),
             "\nhr_hazec:\n" + defb(hz)]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: board from row %d, %d..%d pixels a square"
          % (path, A.TOP, A.PTAB[A.TOP], A.PTAB[A.H - 1]))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "harrierdata.z80s"))
