#!/usr/bin/env python3
"""Generate jetdata.z80s: the pilot, as a stream chequer6 plays back.

    python3 tests/mkjetdata.py

The sprite is 32x96 with a black outline and no mask - a byte with only
one pixel covered has its other pixel given to the outline, so every
byte the pilot draws is a whole byte (see tests/jetpack.py). What is
left is a run-length stream, one entry a row:

    rep                 how many screen rows these ops draw. Two thirds
                        of the pilot's rows are the same as the one
                        above, so 96 rows come out as 47 entries
    ops                 0x01..0x10  skip n bytes
                        0x20+n      copy the n bytes that follow
                        0x40+n      fill n bytes with the byte that follows
                        0x00        end of row
    0x00                in place of a rep, the end of the stream
    0xFF lo hi          in place of a rep, the stream continues there

That last one is why this is a stream and not a bitmap: the free memory
under the screen is in pieces, and the pilot goes in whatever is left of
them once the board's run bank has had its share.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jetpack as J

X = 112                         # where the pilot stands, in pixels
Y = 48                          # and its top row
SPLIT = 97                      # the first row the board redraws


def encode(by, on):
    """One row's ops, over the 16 bytes the pilot is wide."""
    out, i = [], 0
    while i < len(on):
        if not on[i]:
            n = 0
            while i + n < len(on) and not on[i + n]:
                n += 1
            i += n
            if i < len(on):             # a skip at the end of a row is
                out.append([n])         # the end of the row
            continue
        n = 0
        while i + n < len(on) and on[i + n]:
            n += 1
        j = 0
        while j < n:                    # fills where they pay, copies else
            k = 1
            while j + k < n and by[i + j + k] == by[i + j]:
                k += 1
            if k >= 3:
                out.append([0x40 + k, by[i + j]])
                j += k
                continue
            m = j
            while m < n:
                kk = 1
                while m + kk < n and by[i + m + kk] == by[i + m]:
                    kk += 1
                if kk >= 3:
                    break
                m += kk
            out.append([0x20 + m - j] + by[i + j:i + m])
            j = m
        i += n
    return [b for op in out for b in op] + [0]


def stream(rows, y0, y1):
    """The rows from y0 up to y1, with the repeats collapsed."""
    out, y = [], y0
    while y < y1:
        n = 1
        while y + n < y1 and rows[y + n - Y] == rows[y - Y]:
            n += 1
        by, on = rows[y - Y]
        out += [n] + encode(by, on)
        y += n
    return out + [0]


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(here, gap=200):
    rows = J.rows(J.pilot())
    sky = stream(rows, Y, SPLIT)
    floor = stream(rows, SPLIT, Y + J.H)
    drawn = sum(1 for by, on in rows for o in on if o)

    # the sky half goes wherever there is room for it; the half the board
    # draws over goes with the code, and the two are one stream with a
    # jump between them if they have to be split
    parts = ["; Generated by tests/mkjetdata.py - do not edit by hand.",
             "\nJET_X:          EQU %d          ; the pilot's left edge" % X,
             "JET_Y:          EQU %d          ; and its top row" % Y,
             "JET_SPLIT:      EQU %d          ; where the board starts"
             % SPLIT,
             "JET_W:          EQU %d           ; bytes wide" % (J.W // 2),
             "\njet_sky:        ; the rows above the board, drawn once",
             defb(sky),
             "\njet_floor:      ; and the rows the board draws over",
             defb(floor)]
    open(os.path.join(here, "jetdata.z80s"), "w").write(
        "\n".join(parts) + "\n")
    entries = sum(1 for st in (sky, floor) for i, v in enumerate(st)
                  if False) or None
    nrow = 0
    for st, y0, y1 in ((sky, Y, SPLIT), (floor, SPLIT, Y + J.H)):
        y = y0
        while y < y1:
            n = 1
            while y + n < y1 and rows[y + n - Y] == rows[y - Y]:
                n += 1
            nrow += 1
            y += n
    print("pilot: %d bytes drawn of %d, %d rows of stream for %d scanlines, "
          "%d bytes (%d sky, %d board)"
          % (drawn, J.W // 2 * J.H, nrow, J.H, len(sky) + len(floor),
             len(sky), len(floor)))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
