#!/usr/bin/env python3
"""Generate jetdata.z80s: the pilot, as a stream chequer6 plays back.

    python3 tests/mkjetdata.py

The sprite is 32x96 with a black outline and no mask - a byte with only
one pixel covered has its other pixel given to the outline, so every
byte the pilot draws is a whole byte (see tests/jetpack.py). What is
left is a run-length stream, one entry a row:

    rep                 how many screen rows these ops draw. Two thirds
                        of the pilot's rows are the same as the one
                        above, so 96 rows come out as 47 entries
    ops                 0x01..0x10  skip n bytes
                        0x20+n      copy the n bytes that follow
                        0x40+n      fill n bytes with the byte that follows
                        0x00        end of row
    0x00                in place of a rep, the end of the stream
    0xFF lo hi          in place of a rep, the stream continues there

That last one is why this is a stream and not a bitmap: the free memory
under the screen is in pieces, and the pilot goes in whatever is left of
them once the board's run bank has had its share.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jetpack as J

X = 112                         # where the pilot stands, in pixels
Y = 48                          # and its top row
SPLIT = 97                      # the first row the board redraws


def encode(by, kind):
    """One row's ops, over the 16 bytes the pilot is wide.

    A byte with one pixel covered is a mask op of its own - there are
    about two a row, and they are what keeps the outline one pixel wide
    where the silhouette does not land on a byte.
    """
    out, i, n = [], 0, len(kind)
    while i < n:
        if not kind[i]:
            k = 0
            while i + k < n and not kind[i + k]:
                k += 1
            i += k
            if i < n:                   # a skip at the end of a row is
                out.append([k])         # the end of the row
            continue
        if kind[i] > 1:                 # one pixel of it: 0x60 keeps the
            out.append([0x5E + kind[i], by[i]])         # screen's right
            i += 1                                      # pixel, 0x61 its
            continue                                    # left
        j = i
        while j < n and kind[j] == 1:
            j += 1
        while i < j:                    # fills where they pay, copies else
            k = 1
            while i + k < j and by[i + k] == by[i]:
                k += 1
            if k >= 3:
                out.append([0x40 + k, by[i]])
                i += k
                continue
            m = i
            while m < j:
                kk = 1
                while m + kk < j and by[m + kk] == by[m]:
                    kk += 1
                if kk >= 3:
                    break
                m += kk
            out.append([0x20 + m - i] + by[i:m])
            i = m
    return [b for op in out for b in op] + [0]


def stream(rows, y0, y1):
    """The rows from y0 up to y1, with the repeats collapsed."""
    out, y = [], y0
    while y < y1:
        n = 1
        while y + n < y1 and rows[y + n - Y] == rows[y - Y]:
            n += 1
        by, kind = rows[y - Y]
        out += [n] + encode(by, kind)
        y += n
    return out + [0]


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(here):
    parts = ["; Generated by tests/mkjetdata.py - do not edit by hand.",
             "\nJET_X:          EQU %d          ; the pilot's left edge" % X,
             "JET_Y:          EQU %d          ; and its top row" % Y,
             "JET_SPLIT:      EQU %d          ; where the board starts"
             % SPLIT,
             "JET_W:          EQU %d           ; bytes wide" % (J.W // 2),
             "JET_POSES:      EQU 3           ; banking left, level, right",
             "\njet_pose:       ; the two halves of each pose",
             "\n".join("        DEFW jet_sky%d,jet_floor%d" % (k, k)
                       for k in range(3))]
    tot = 0
    for k, way in enumerate((-1, 0, 1)):
        rows = J.rows(J.lean(J.pilot(), way))
        sky = stream(rows, Y, SPLIT)
        floor = stream(rows, SPLIT, Y + J.H)
        tot += len(sky) + len(floor)
        parts += ["\njet_sky%d:       ; the rows above the board, drawn"
                  " once a pose" % k,
                  defb(sky),
                  "\njet_floor%d:     ; and the rows the board draws over"
                  % k,
                  defb(floor)]
    open(os.path.join(here, "jetdata.z80s"), "w").write(
        "\n".join(parts) + "\n")
    rows = J.rows(J.pilot())
    drawn = sum(1 for by, kind in rows for k in kind if k)
    masked = sum(1 for by, kind in rows for k in kind if k > 1)
    print("pilot: %d bytes drawn of %d, %d of them one pixel; three poses, "
          "%d bytes of stream"
          % (drawn, J.W // 2 * J.H, masked, tot))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
