#!/usr/bin/env python3
"""Compile the pilot so that he can be drawn anywhere: jetmove.z80s.

    python3 tests/mkjetmove.py

chequer8's compiled pilot is 96 rows in 14,400 T-states and every
address in it is absolute, which is only possible because he stands
still. chequer9's moves, so the same trick has to be made relative -
and the way to do that on a Z80 is to do everything through the stack
pointer, because SP is the only pointer with an add:

    a run of solid bytes    PUSH DE a pair, 5.5 T-states a byte, with
                            DE reloaded only where the pair changes
    a single byte           POP BC / LD C,n / PUSH BC, which reads the
                            byte beside it and writes it back unchanged
    one pixel of pilot      POP BC / AND / OR / PUSH BC, the only
                            read-modify-write left
    getting there           LD HL,-d / ADD HL,SP / LD SP,HL, or DEC SP
                            where the step is small enough

The walk itself is mksprite.py's, because the tree wants the same
thing: one descending pass of SP over a masked shape. What it costs
against an absolute version is the steps - 16,116 T-states against
14,401 at 32x96, measured in the frame - and what it buys is that he
can go anywhere.

HE MOVES IN WHOLE BYTES sideways, which is two pixels. A pixel of
horizontal travel would want the sprite compiled at both phases and
a mask on every byte of him rather than 110 of them; two pixel steps
at 25 Hz are not visible as steps on a sprite this size.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jetpack as J                                     # noqa: E402
import mksprite as S                                    # noqa: E402

W = J.W // 2                    # bytes wide
BANK = 0x20 + int(os.environ.get("JET_FIRST", 24))      # LMPR: RAM over
                                # ROM 0, and the page the map has spare
                                # past the desert's
WINDOW = 0x7F00                 # what LMPR maps, less the caller's stack


def main(here):
    parts = ["; Generated by tests/mkjetmove.py - do not edit by hand.",
             "; The pilot as code that can be drawn anywhere: one walk of",
             "; the stack pointer from the bottom right corner of his box",
             "; to the top left. The caller puts SP there and jumps in;",
             "; CQ9_RET, from the resident assembly, is the way back.",
             "\n        ORG 0x0000",
             "jet_move:       ; banking left, level, right",
             "        DEFW jet_m0,jet_m1,jet_m2",
             "\nJET_W:          EQU %d           ; bytes wide" % W,
             "JET_H:          EQU %d           ; and scanlines tall" % J.H]
    ts = []
    for k, way in enumerate((-1, 0, 1)):
        out, t = S.walk("jet_m%d" % k, J.rows(J.lean(J.pilot(), way)),
                        W, J.H, "CQ9_RET")
        parts += out
        ts.append(t)
    parts.append("\n        ASSERT $ <= 0x%04X       ; the window, less the"
                 " caller's stack" % WINDOW)
    open(os.path.join(here, "jetmove.z80s"), "w").write("\n".join(parts) + "\n")
    open(os.path.join(here, "jetmoveequ.z80s"), "w").write(
        "; Generated by tests/mkjetmove.py - do not edit by hand.\n"
        "; What the resident code needs to know about the pilot's page.\n"
        "\nJET_BANK:       EQU 0x%02X      ; LMPR: RAM over ROM 0\n"
        "JET_POSE:       EQU 0x0000      ; the table of poses, at its foot\n"
        "JET_W:          EQU %d\nJET_H:          EQU %d\n"
        % (BANK, W, J.H))
    print("jetmove.z80s: three poses, %d T-states each by the instruction "
          "count (%d, %d, %d)" % (sum(ts) // 3, *ts))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
