#!/usr/bin/env python3
"""Generate portaldata.z80s: the maze portal.z80s walks.

    python3 tests/mkportaldata.py

Three tables. The vertices, in the order p_xform transforms them; the
walls, four bytes each - two vertices, a colour ramp base, and the
sector behind the wall or 255 if it is solid; and the sectors, three
bytes each - where their walls start and how many there are.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import portal as P


def main(path):
    parts = ["; Generated by tests/mkportaldata.py - do not edit by hand.",
             "\nP_NV:           EQU %d          ; vertices in the maze"
             % len(P.VERTS),
             "P_NS:           EQU %d           ; and convex sectors"
             % len(P.SECTORS),
             "\np_vert:         ; the maze, in world units"]
    for x, z in P.VERTS:
        parts.append("        DEFW %d,%d" % (x, z))
    parts.append("\np_sect0:        ; where each sector's walls are")
    for i in range(len(P.SECTORS)):
        parts.append("        DEFW p_w%d\n        DEFB %d"
                     % (i, len(P.SECTORS[i])))
    parts.append("\n                ; v0, v1, colour ramp, sector behind")
    for i, walls in enumerate(P.SECTORS):
        parts.append("p_w%d:" % i)
        for v0, v1, col, behind in walls:
            parts.append("        DEFB %d,%d,%d,%d"
                         % (v0, v1, col, 255 if behind is None else behind))
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: %d vertices, %d sectors, %d walls, %d of them doors"
          % (path, len(P.VERTS), len(P.SECTORS),
             sum(len(w) for w in P.SECTORS),
             sum(1 for w in P.SECTORS for x in w if x[3] is not None)))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "portaldata.z80s"))
