#!/usr/bin/env python3
"""Generate prismpredata.z80s and prismprepts.z80s from tests/prismpre.py.

Two files because the tables do not fit in one place: the records go
in the low 8K with the code, and the seven kilobytes of projected
point go above the screen buffers, below the bench's stack.

    python3 tests/mkprismpredata.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bench import Bench
import prismpre as PP
import prism as P

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def rows(name, data, per=16):
    out = ["%s:" % name]
    for i in range(0, len(data), per):
        out.append("        DEFB " + ",".join(str(b) for b in data[i:i + per]))
    return "\n".join(out)


def main():
    b = Bench("harness_prism.asm", org=0)
    s = b.syms
    recip = list(b.peek(s["t3d_recip"], 256))
    lite = [x - 256 if x > 127 else x for x in b.peek(s["rndl_lite"], 3)]
    recs, pts, _ = PP.build(recip, lite)
    base = [c for _, c in P.PIECES]

    stem = "entropypre" if P.LOGO == "entropy" else "prismpre"
    # The points do not fit in one place once the logo has nine
    # pieces: 0xE000 to the stack is 7,680 bytes and a frame is
    # PP.PTS. So a frame's points are found through a table of
    # pointers, and as many frames as fit go above the buffers with
    # the rest down in the low 8K beside the records.
    high = min(PP.NFRAMES, 7680 // PP.PTS)
    ptr = "\n".join(
        "        DEFW pp_ptshi + %d" % (PP.PTS * f) if f < high else
        "        DEFW pp_ptslo + %d" % (PP.PTS * (f - high))
        for f in range(PP.NFRAMES))

    p = os.path.join(ROOT, stem + "data.z80s")
    with open(p, "w") as f:
        f.write(""";------------------------------------------------------------------
; Generated by tests/mkprismpredata.py - do not edit.
;
; One %d-byte record a frame: the pieces farthest first, the four
; bytes of erase box renderlit keeps, then the face nibbles - the ramp
; level, bit 3 set when the face is turned away. Then where each
; frame's points are, and the frames of them that did not fit above
; the screen buffers.
;------------------------------------------------------------------

PP_NF:          EQU %d      ; frames in the loop
PP_NP:          EQU %d      ; pieces
PP_REC:         EQU %d      ; bytes of record a frame
PP_PTS:         EQU %d      ; bytes of point a frame

%s

%s

pp_ptr:         ; where each frame's points are
%s

%s
""" % (PP.REC, PP.NFRAMES, len(P.PIECES), PP.REC, PP.PTS,
       rows("pp_base", base, 8), rows("pp_recs", recs), ptr,
       rows("pp_ptslo", pts[high * PP.PTS:])))

    q = os.path.join(ROOT, stem + "pts.z80s")
    with open(q, "w") as f:
        f.write(""";------------------------------------------------------------------
; Generated by tests/mkprismpredata.py - do not edit.
;
; Every frame's projected corners: %d pieces of eight (sx, sy), in
; renderlit's vertex order, %d bytes a frame - the %d frames of them
; that fit above the screen buffers.
;------------------------------------------------------------------

%s
""" % (len(P.PIECES), PP.PTS, high, rows("pp_ptshi", pts[:high * PP.PTS])))

    print("wrote %s: %d of record, %d of point (%d frames)"
          % (p, len(recs), len(pts) - high * PP.PTS, PP.NFRAMES - high))
    print("wrote %s: %d of point (%d frames)"
          % (q, high * PP.PTS, high))
    return 0


if __name__ == "__main__":
    sys.exit(main())
