#!/usr/bin/env python3
"""Generate prismdata.z80s: the logo, its faces and its normals.

    python3 tests/mkprismdata.py

Everything comes out of tests/prism.py, which is the model the Z80 is
checked against. What the Z80 needs that the model works out on the
fly is: the eight vertices of each piece in renderlit's index order,
each face's normal and plane offset, the distinct coordinate values
(so that a frame builds only the multiply table entries it will read),
and each piece's centre, which is what orders them.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import prism as P


def defb(v, per=12):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(path):
    norms, faces, verts, base = [], [], [], []
    for quad, b in P.PIECES:
        base.append(b)
        for x, y, z in P.verts(quad):
            verts += [x, y, z]
        for n, off in P.normals(quad):
            if n not in norms:
                norms.append(n)
            faces += [norms.index(n), (64 * off) & 0xFF, (64 * off) >> 8 & 0xFF]
    for i, mask in enumerate(P.BURIED):             # bit 7: never drawn
        for e in range(4):
            if (mask >> e) & 1:
                faces[3 * (6 * i + e)] |= 0x80

    vals = [sorted(set(v[a] for v in
                       [P.verts(q)[i] for q, _ in P.PIECES for i in range(8)]))
            for a in range(3)]

    parts = ["; Generated by tests/mkprismdata.py - do not edit by hand.",
             "\nPR_NP:          EQU %d           ; convex pieces" % len(P.PIECES),
             "PR_NN:          EQU %d          ; distinct face normals"
             % len(norms),
             "PR_TZ:          EQU %d       ; how far away the logo sits"
             % P.TZ,
             "PR_NPAIR:       EQU %d          ; pairs of pieces to order"
             % len(P.PAIRS),
             "PR_MASK:        EQU %d         ; a bit a piece"
             % ((1 << len(P.PIECES)) - 1),
             "PR_OVO:         EQU %d          ; pr_ov, from pr_fr"
             % (2 * len(P.PIECES)),
             "\npr_da:          ; how fast the logo turns, an axis at a time",
             defb(P.SPIN),
             "PR_DA:          EQU pr_da",
             "\npr_vert:        ; eight vertices a piece, in renderlit's order",
             defb(verts, 12),
             "\npr_base:        ; and which ramp each piece wears",
             defb(base),
             "\npr_pair:        ; every pair of pieces, and a face of the",
             "                ; first whose plane has the second wholly",
             "                ; outside it - which settles their order.",
             "                ; Where its offset is, where pr_light will",
             "                ; leave that normal's N.T, then the two",
             "\n".join("        DEFW pr_face + %d, pr_nsh + %d\n"
                        "        DEFB %d, %d"
                        % (3 * f + 1, 3 * (faces[3 * f] & 0x7F) + 1, i, j)
                        for i, j, f in P.PAIRS),
             "\npr_bit:         ; a bit a piece, a word each",
             "\n".join("        DEFW %d" % (1 << i)
                        for i in range(len(P.PIECES))),
             "\npr_norm:        ; every normal any face has, 1.7 signed",
             defb([c for n in norms for c in n], 12),
             "\npr_face:        ; a normal and a plane offset, six a piece",
             defb(faces, 12)]
    parts.append("\npr_axes:        ; where each axis's values are, and how")
    parts.append("                ; many - a frame builds only these")
    for a, name in enumerate("xyz"):
        parts.append("        DEFW pr_%sv\n        DEFB %d"
                     % (name, len(vals[a])))
    for a, name in enumerate("xyz"):
        parts.append("\npr_%sv:         ; the %s a vertex ever has"
                     % (name, name))
        parts.append(defb(vals[a], 12))
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: %d pieces, %d faces, %d normals, %d/%d/%d coordinate "
          "values" % (path, len(P.PIECES), len(faces) // 3, len(norms),
                      len(vals[0]), len(vals[1]), len(vals[2])))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    name = "entropydata.z80s" if P.LOGO == "entropy" else "prismdata.z80s"
    main(os.path.join(here, name))
