#!/usr/bin/env python3
"""Generate prismdata.z80s: the logo, its faces and its normals.

    python3 tests/mkprismdata.py

Everything comes out of tests/prism.py, which is the model the Z80 is
checked against. What the Z80 needs that the model works out on the
fly is: the eight vertices of each piece in renderlit's index order,
each face's normal and plane offset, the distinct coordinate values
(so that a frame builds only the multiply table entries it will read),
and each piece's centre, which is what orders them.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import prism as P


def defb(v, per=12):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(path):
    norms, faces, verts, cen, base = [], [], [], [], []
    for quad, b in P.PIECES:
        base.append(b)
        for x, y, z in P.verts(quad):
            verts += [x, y, z]
        cen += [sum(p[0] for p in quad) // 4, sum(p[1] for p in quad) // 4]
        for n, off in P.normals(quad):
            if n not in norms:
                norms.append(n)
            faces += [norms.index(n), (64 * off) & 0xFF, (64 * off) >> 8 & 0xFF]

    vals = [sorted(set(v[a] for v in
                       [P.verts(q)[i] for q, _ in P.PIECES for i in range(8)]))
            for a in range(3)]

    parts = ["; Generated by tests/mkprismdata.py - do not edit by hand.",
             "\nPR_NP:          EQU %d           ; convex pieces" % len(P.PIECES),
             "PR_NN:          EQU %d          ; distinct face normals"
             % len(norms),
             "PR_TZ:          EQU %d       ; how far away the logo sits"
             % P.TZ,
             "\npr_vert:        ; eight vertices a piece, in renderlit's order",
             defb(verts, 12),
             "\npr_base:        ; and which ramp each piece wears",
             defb(base),
             "\npr_cen:         ; its centre, which is what orders it",
             defb(cen),
             "\npr_norm:        ; every normal any face has, 1.7 signed",
             defb([c for n in norms for c in n], 12),
             "\npr_face:        ; a normal and a plane offset, six a piece",
             defb(faces, 12)]
    for a, name in enumerate("xyz"):
        parts.append("\npr_%sn:          EQU %d" % (name, len(vals[a])))
        parts.append("pr_%sv:         ; the %s values a vertex ever has"
                     % (name, name))
        parts.append(defb(vals[a], 12))
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: %d pieces, %d faces, %d normals, %d/%d/%d coordinate "
          "values" % (path, len(P.PIECES), len(faces) // 3, len(norms),
                      len(vals[0]), len(vals[1]), len(vals[2])))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "prismdata.z80s"))
