#!/usr/bin/env python3
"""Generate prismpredata.z80s and prismprepts.z80s from tests/prismpre.py.

Two files because the tables do not fit in one place: the records go
in the low 8K with the code, and the seven kilobytes of projected
point go above the screen buffers, below the bench's stack.

    python3 tests/mkprismpredata.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bench import Bench
import prismpre as PP
import prism as P

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def rows(name, data, per=16):
    out = ["%s:" % name]
    for i in range(0, len(data), per):
        out.append("        DEFB " + ",".join(str(b) for b in data[i:i + per]))
    return "\n".join(out)


def main():
    b = Bench("harness_prism.asm", org=0)
    s = b.syms
    recip = list(b.peek(s["t3d_recip"], 256))
    lite = [x - 256 if x > 127 else x for x in b.peek(s["rndl_lite"], 3)]
    recs, pts, _ = PP.build(recip, lite)
    base = [c for _, c in P.PIECES]

    p = os.path.join(ROOT, "prismpredata.z80s")
    with open(p, "w") as f:
        f.write(""";------------------------------------------------------------------
; Generated by tests/mkprismpredata.py - do not edit.
;
; One 32-byte record a frame: seven pieces farthest first, the four
; bytes of erase box renderlit keeps, then 42 face nibbles - the ramp
; level, bit 3 set when the face is turned away.
;------------------------------------------------------------------

PP_NF:          EQU %d      ; frames in the loop
PP_NP:          EQU %d      ; pieces
PP_REC:         EQU %d      ; bytes of record a frame
PP_PTS:         EQU %d      ; bytes of point a frame

%s

%s
""" % (PP.NFRAMES, len(P.PIECES), PP.REC, PP.PTS,
       rows("pp_base", base, 8), rows("pp_recs", recs)))

    q = os.path.join(ROOT, "prismprepts.z80s")
    with open(q, "w") as f:
        f.write(""";------------------------------------------------------------------
; Generated by tests/mkprismpredata.py - do not edit.
;
; Every frame's projected corners: seven pieces of eight (sx, sy), in
; renderlit's vertex order, %d bytes a frame.
;------------------------------------------------------------------

%s
""" % (PP.PTS, rows("pp_pts", pts)))

    print("wrote %s: %d bytes of record" % (p, len(recs)))
    print("wrote %s: %d bytes of point" % (q, len(pts)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
