#!/usr/bin/env python3
"""Run the demo tests and check their reports into reports/.

    python3 tests/mkreports.py              # the demo family, as listed
    python3 tests/mkreports.py chequer9     # or just some of them
    python3 tests/mkreports.py --all        # everything in tests/

Every number quoted in costs.md, tricks.md and the design notes came out
of one of these runs, and until now the runs were something you had to
do yourself to check a claim. This writes each one to reports/<name>.txt
so the numbers in the notes can be diffed against the machine that
produced them - and so that a change which costs 3,000 T-states shows up
as a diff rather than as a number nobody re-read.

They are slow on purpose: each one draws every frame twice, once on an
emulated Z80 and once in Python, and compares them byte for byte. The
default list is the demos whose costs the notes actually quote; --all
adds the arithmetic and geometry tests, some of which are exhaustive
over 16-bit inputs and take much longer than the demos do.
"""
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "reports")

STUDIES = {"budget": "mkbudget.py"}     # not a test but a study, and its
                                        # report is read the same way

DEMOS = ("chequer", "chequer2", "chequer3", "chequer4", "chequer5",
         "chequer6", "chequer7", "chequer8", "chequer9", "chequer10",
         "harrier", "road", "road2", "zarch", "democube", "renderlit",
         "portal", "wolf3d", "twist", "roto", "vox", "prismpre",
         "snd", "budget")


def run(name, timeout=900):
    """One test, its output to reports/<name>.txt, and what it took."""
    t0 = time.time()
    script = STUDIES.get(name, "test_%s.py" % name)
    r = subprocess.run([sys.executable, os.path.join(HERE, script)],
                       capture_output=True, text=True, timeout=timeout)
    took = time.time() - t0
    body = r.stdout + (("\n" + r.stderr) if r.returncode else "")
    head = ("# tests/%s\n#\n" % script
            + "# Generated by tests/mkreports.py - do not edit by hand.\n"
            + "# %s, %.0f seconds on the machine that wrote it.\n\n"
            % ("passed" if not r.returncode else "FAILED", took))
    open(os.path.join(OUT, "%s.txt" % name), "w").write(head + body)
    return r.returncode, took


def main(argv):
    os.makedirs(OUT, exist_ok=True)
    names = list(argv)
    if names == ["--all"]:
        names = sorted(f[5:-3] for f in os.listdir(HERE)
                       if f.startswith("test_") and f.endswith(".py"))
    names = names or list(DEMOS)
    bad = 0
    for name in names:
        try:
            rc, took = run(name)
        except subprocess.TimeoutExpired:
            rc, took = 1, float("nan")
            open(os.path.join(OUT, "%s.txt" % name), "w").write(
                "# tests/%s\n#\n# TIMED OUT.\n"
                % STUDIES.get(name, "test_%s.py" % name))
        bad += bool(rc)
        print("  %-12s %s %6.0fs  reports/%s.txt"
              % (name, "ok    " if not rc else "FAILED", took, name))
    print("\n%s" % ("ALL REPORTS WRITTEN" if not bad
                    else "FAILURES: %d" % bad))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
