#!/usr/bin/env python3
"""Generate rotodata.z80s: the 16 by 16 texture roto.z80s samples.

    python3 tests/mkrotodata.py

Page aligned, and both nibbles of a byte the same, so one texel is one
screen byte of two pixels.
"""
import math
import os


def texture():
    t = []
    for r in range(16):
        for c in range(16):
            d = math.hypot(r - 7.5, c - 7.5)
            if ((r >> 2) + (c >> 2)) & 1:
                v = 8 + min(7, int(d))
            else:
                v = 1 + min(6, int(14 - d))
            t.append((v << 4) | v)
    return t


def main(path):
    t = texture()
    open(path, "w").write(
        "; Generated by tests/mkrotodata.py - do not edit by hand.\n"
        "\n        ALIGN 256\nrz_tex:\n"
        + "\n".join("        DEFB " + ",".join(str(x) for x in t[i:i + 16])
                     for i in range(0, 256, 16)) + "\n")
    print("wrote %s: 16 by 16 texels, 256 bytes" % path)


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "rotodata.z80s"))
