#!/usr/bin/env python3
"""Generate roaddata.z80s: the tables road.z80s reads.

    python3 tests/mkroaddata.py

All of it is fixed by the camera height and the track, neither of which
changes, so none of it is built on the Z80.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import road as A
from mkchqdata import defb, defw, sam


def rows():
    """Eight bytes a scanline, bottom row first - the order it draws in.

    The depth, the rails the centre is held between so that no boundary
    can leave the screen, the three magnitudes the six boundaries are
    made of, and a byte for the frame to write its parities into.
    """
    out = []
    for y in range(A.H - 1, A.HZ, -1):
        lo, hi = A.CLAMP[y]
        w, k, s = A.WTAB[y], A.KTAB[y], A.STAB[y]
        out += [A.ZTAB[y] & 255, A.ZTAB[y] >> 8, lo, hi, w, w - k, s, 0]
    return out


def mixed():
    """A boundary lands mid-byte: the PUSH that straddles it.

    Four offsets for each pair of colours that meet at a boundary. A
    PUSH writes its low register at the lower address, which is the
    left hand pair of pixels, so C carries them.
    """
    out = []
    for c, n in PAIRS:
        for t in range(4):
            px = [n if i < t else c for i in range(4)]
            out += [(px[0] << 4) | px[1], (px[2] << 4) | px[3]]
    return out


G, T, K, L = A.GRASS, A.TARMAC, A.KERB, A.LINE
PAIRS = [(G, K), (K, T), (T, L), (L, T), (T, K), (K, G), (G, T), (T, G)]
NAMES = ["GK", "KT", "TL", "LT", "TK", "KG", "GT", "TG"]


def fog():
    """Six palette bytes a scanline: grass, tarmac and kerb, both ways.

    Everything that repeats with distance lives here rather than in the
    pixels - the mown stripes, the tarmac's bands and the kerb's red and
    white all swap when the scanline's parity does - and so does the
    fade into the horizon, which therefore costs nothing either. Above
    the horizon the first pair is the sky, and the rest is never read.
    """
    def mix(a, b, t):
        return [x + (y - x) * t for x, y in zip(a, b)]

    sky = (2, 4, 6)                     # what everything fades into
    out = []
    for y in range(A.H):
        if y <= A.HZ:
            t = y / A.HZ
            c = mix((0, 0, 4), sky, t)
            out += [sam(*c), sam(*c), 0, 0, 0, 0]
        else:
            t = 1 - (y - A.HZ) / (A.H - A.HZ)       # 0 near, 1 far
            t *= t                                  # squared, because the
                                                    # top few rows of road
                                                    # are most of the
                                                    # distance in them
            out += [sam(*mix((0, 4, 0), sky, t)),
                    sam(*mix((0, 6, 2), sky, t)),
                    sam(*mix((2, 2, 2), sky, t)),
                    sam(*mix((4, 4, 4), sky, t)),
                    sam(*mix((6, 0, 0), sky, t)),
                    sam(*mix((6, 6, 6), sky, t))]
    return out


def bands():
    """How many rows draw with seven spans, five and three.

    Which spans a row has is fixed by the row: a kerb narrower than
    four pixels is not drawn at all, and neither is a centre line, so
    the screen comes in three bands and the chain is patched twice a
    frame rather than tested once a span.
    """
    a = sum(1 for y in range(A.H) if A.STAB[y])
    b = sum(1 for y in range(A.H) if A.KTAB[y]) - a
    return a, b, A.H - 1 - A.HZ - a - b


def main(path):
    na, nb, nc = bands()
    parts = ["; Generated by tests/mkroaddata.py - do not edit by hand.",
             "\nRD_HZ:          EQU %d" % A.HZ,
             "RD_TOP:         EQU %d          ; first row with road on it"
             % (A.HZ + 1),
             "RD_NA:          EQU %d          ; rows with a centre line" % na,
             "RD_NB:          EQU %d          ; rows with kerbs but none"
             % nb,
             "RD_NC:          EQU %d          ; and rows with neither" % nc,
             "\nRD_GRASS:       EQU 0x%02X%02X" % (G * 17, G * 17),
             "RD_TARMAC:      EQU 0x%02X%02X" % (T * 17, T * 17),
             "RD_KERB:        EQU 0x%02X%02X" % (K * 17, K * 17),
             "RD_LINE:        EQU 0x%02X%02X" % (L * 17, L * 17),
             "RD_WHITE:       EQU %d         ; what a dash is painted in"
             % sam(6, 6, 6)]
    parts += ["\n; where each pair of colours starts in rd_mx"]
    parts += ["RD_M%s:         EQU %d" % (n, 8 * i) for i, n in enumerate(NAMES)]
    parts += ["\n        ALIGN 256\nrd_mx:\n" + defb(mixed()),
              "\n        ALIGN 256\nrd_trk:\n" + defw(A.TRACK),
              "\n        ALIGN 256\nrd_fog:\n" + defb(fog()),
              "\nrd_row:\n" + defb(rows(), 8)]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: %d rows of road, bands of %d, %d and %d, "
          "%d..%d pixels of road" % (path, A.H - 1 - A.HZ, na, nb, nc,
                                     2 * A.WTAB[A.HZ + 1], 2 * A.WTAB[A.H - 1]))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "roaddata.z80s"))
