#!/usr/bin/env python3
"""Generate shakudata.z80s - the flute's tables, from tests/shaku.py.

    python3 tests/mkshakudata.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import shaku as K

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sb(v):
    return v & 0xFF             # a signed byte, as the assembler wants it


def main():
    o = []
    w = o.append
    w(";------------------------------------------------------------------")
    w("; shakudata.z80s - generated by tests/mkshakudata.py, do not edit")
    w(";")
    w("; The notes the flute has, the envelope, the vibrato and the phrase.")
    w(";------------------------------------------------------------------")
    w("")
    w("SK_ENVLEN:      EQU %d          ; rows of attack and swell" % len(K.ENV))
    w("SK_RELLEN:      EQU %d           ; and of release" % len(K.REL))
    w("SK_VIBLEN:      EQU %d          ; frames a vibrato cycle: 50/12 = 4.2 Hz"
      % K.VIB_LEN)
    w("SK_VIBRAMP:     EQU %d          ; frames until it is at full depth"
      % K.VIB_RAMP)
    w("SK_NOTES:       EQU %d           ; notes and rests in the phrase"
      % len(K.PHRASE))
    w("SK_INITS:       EQU %d          ; registers sk_init sets up"
      % len(K.INIT))
    w("SK_H2:          EQU %d           ; 2f is this much quieter than f" % K.H2)
    w("SK_H4:          EQU %d           ; and 4f this much" % K.H4)
    w("SK_REST:        EQU %d         ; a rest, in the phrase" % K.REST)
    w("")
    w("; each note: frequency byte, the octave register pair for f and 2f,")
    w("; and the one for 4f and the breath")
    w("sk_notes:")
    for i, (octave, n) in enumerate(K.NOTE):
        w("        DEFB %3d,0x%02X,0x%02X            ; %-3s %6.1f Hz"
          % (n, octave | ((octave + 1) << 4),
             (octave + 2) | (K.NOISE_OCT << 4), K.NAMES[i], K.hz(n, octave)))
    w("")
    w("; tone level, noise level, pitch offset - by frame from the start")
    w("sk_env:")
    for ta, na, po in K.ENV:
        w("        DEFB %3d,%3d,%3d" % (ta, na, sb(po)))
    w("")
    w("; and by frames remaining, at the end")
    w("sk_rel:")
    for ta, na, po in K.REL:
        w("        DEFB %3d,%3d,%3d" % (ta, na, sb(po)))
    w("")
    w("; the vibrato: %d frames of it coming in, then one cycle for ever"
      % K.VIB_RAMP)
    w("sk_vin:")
    for i in range(0, len(K.VIN), 12):
        w("        DEFB " + ",".join("%3d" % sb(v) for v in K.VIN[i:i + 12]))
    w("sk_vst:")
    w("        DEFB " + ",".join("%3d" % sb(v) for v in K.VST))
    w("")
    w("; the phrase: note, frames")
    w("sk_phrase:")
    for note, dur in K.PHRASE:
        name = "rest" if note == K.REST else K.NAMES[note]
        w("        DEFB %3d,%3d                ; %-4s %5.2f s"
          % (note, dur, name, dur / 50.0))
    w("")
    w("; what sk_init sends: register, value")
    w("sk_ini:")
    for r, v in K.INIT:
        w("        DEFB 0x%02X,0x%02X" % (r, v))
    w("")
    path = os.path.join(ROOT, "shakudata.z80s")
    open(path, "w").write("\n".join(o) + "\n")
    print("%s: %d notes, %d phrase entries" % (path, len(K.NOTE), len(K.PHRASE)))


if __name__ == "__main__":
    main()
