#!/usr/bin/env python3
"""Generate stormdata.z80s - the storm's two scores, in the chip's bytes.

    python3 tests/mkstormdata.py

The scores in tests/storm.py are written in Hz and 0..1 levels. This
turns them into octaves, frequency bytes and 8.8 per-frame steps, and
splits any segment that would cross an octave boundary.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import storm as S

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def w16(v):
    return v & 0xFFFF


def segments(name, score, raw, shift):
    o = ["%s:" % name]
    for (frames, octave, n0, nstep, v0, vstep) in score:
        o.append("        DEFB %3d,0x%02X,%3d,%3d,%3d,%3d,%3d,%3d"
                 % (frames, octave << (4 if shift else 0), n0, v0,
                    w16(nstep) & 0xFF, w16(nstep) >> 8,
                    w16(vstep) & 0xFF, w16(vstep) >> 8)
                 + "   ; %5.2f s  %6.1f Hz  level %2d"
                 % (frames / 50.0, S.hz(n0, octave), v0))
    return o


def emit(l0, l1, path, what, script):
    """Write a score pair out as the routine's two layers."""
    o = []
    w = o.append
    w(";------------------------------------------------------------------")
    w("; %s - generated by tests/%s, do not edit" % (os.path.basename(path),
                                                     script))
    w(";")
    w("; %s" % what)
    w(";")
    w("; Two scores of segments. Each is: frames, the octave byte (already")
    w("; in the nibble its register wants), the frequency byte and the")
    w("; level to start at, then the 8.8 step for each of them a frame.")
    w(";------------------------------------------------------------------")
    w("")
    w("SM_L0SEGS:      EQU %d          ; segments in layer 0 (channels 0-2)"
      % len(l0))
    w("SM_L1SEGS:      EQU %d           ; and in layer 1 (channels 3-5)"
      % len(l1))
    w("SM_MAXLVL:      EQU %d          ; three channels of fifteen" % S.MAXLVL)
    w("SM_INITS:       EQU %d          ; registers sm_init sets up" % len(S.INIT))
    w("SM_SEGLEN:      EQU 8           ; bytes a segment")
    w("")
    o += segments("sm_l0", l0, None, False)
    w("")
    o += segments("sm_l1", l1, None, True)
    w("")
    w("; a 0..%d level as three amplitude bytes: the chip only has sixteen"
      % S.MAXLVL)
    w("; steps a channel, and three channels carrying the same noise add up")
    w("sm_spread:")
    for i, three in enumerate(S.SPREAD):
        w("        DEFB 0x%02X,0x%02X,0x%02X            ; %2d"
          % (three[0], three[1], three[2], i))
    w("")
    w("sm_ini:")
    for r, v in S.INIT:
        w("        DEFB 0x%02X,0x%02X" % (r, v))
    w("")
    open(path, "w").write("\n".join(o) + "\n")
    print("%s: %d + %d segments, %d frames"
          % (path, len(l0), len(l1), sum(x[0] for x in l0)))


def main():
    emit(S.TH, S.RN, os.path.join(ROOT, "stormdata.z80s"),
         "Distant thunder, and then rain over the top of it.",
         "mkstormdata.py")


if __name__ == "__main__":
    main()
