#!/usr/bin/env python3
"""Generate starsdata.z80s from tests/stars.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import stars as S

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(b) for b in v[i:i + per])
                     for i in range(0, len(v), per))


def main():
    f = S.Field()
    st = []
    for x, y, z in f.star:
        st += [x & 0xFF, y & 0xFF, z]
    col = [S.RAMP[z >> 5] * 0x11 for z in range(256)]

    p = os.path.join(ROOT, "starsdata.z80s")
    open(p, "w").write("""\
;------------------------------------------------------------------
; Generated by tests/mkstarsdata.py - do not edit.
;------------------------------------------------------------------

ST_N:           EQU %d     ; stars
ST_SPEED:       EQU %d       ; how much nearer one gets a frame
ST_ZMIN:        EQU %d      ; the reciprocal table's floor
ST_YLIM:        EQU %d      ; half the screen, less a pixel
ST_SEED:        EQU 0x%04X   ; where the LFSR stands after the field
                             ; was laid out, so respawns line up

        ALIGN 256
st_recip:       ; 256*64/z, a byte, which is what pins ST_ZMIN
%s

        ALIGN 256
st_col:         ; z -> its shade, in both nibbles
%s

st_star:        ; x, y, z a star
%s
""" % (S.NSTARS, S.SPEED, S.ZMIN, S.YLIM, f.lfsr,
       defb(S.RECIP), defb(col), defb(st, 12)))
    print("wrote %s: %d stars" % (p, S.NSTARS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
