#!/usr/bin/env python3
"""Generate stormdata.z80s - the storm's two scores, in the chip's bytes.

    python3 tests/mkstormdata.py

The scores in tests/storm.py are written in Hz and 0..1 levels. This
turns them into octaves, frequency bytes and 8.8 per-frame steps, and
splits any segment that would cross an octave boundary.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import storm as S

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def w16(v):
    return v & 0xFFFF


def segments(name, score, raw, shift):
    o = ["%s:" % name]
    for (frames, octave, n0, nstep, v0, vstep) in score:
        o.append("        DEFB %3d,0x%02X,%3d,%3d,%3d,%3d,%3d,%3d"
                 % (frames, octave << (4 if shift else 0), n0, v0,
                    w16(nstep) & 0xFF, w16(nstep) >> 8,
                    w16(vstep) & 0xFF, w16(vstep) >> 8)
                 + "   ; %5.2f s  %6.1f Hz  level %2d"
                 % (frames / 50.0, S.hz(n0, octave), v0))
    return o


def main():
    o = []
    w = o.append
    w(";------------------------------------------------------------------")
    w("; stormdata.z80s - generated by tests/mkstormdata.py, do not edit")
    w(";")
    w("; Two scores of segments. Each is: frames, the octave byte (already")
    w("; in the nibble its register wants), the frequency byte and the")
    w("; level to start at, then the 8.8 step for each of them a frame.")
    w(";------------------------------------------------------------------")
    w("")
    w("SM_THSEGS:      EQU %d          ; segments of thunder" % len(S.TH))
    w("SM_RNSEGS:      EQU %d           ; and of rain" % len(S.RN))
    w("SM_MAXLVL:      EQU %d          ; three channels of fifteen" % S.MAXLVL)
    w("SM_INITS:       EQU %d          ; registers sm_init sets up" % len(S.INIT))
    w("SM_SEGLEN:      EQU 8           ; bytes a segment")
    w("")
    o += segments("sm_th", S.TH, S.THUNDER, False)
    w("")
    o += segments("sm_rn", S.RN, S.RAIN, True)
    w("")
    w("; a 0..%d level as three amplitude bytes: the chip only has sixteen"
      % S.MAXLVL)
    w("; steps a channel, and three channels carrying the same noise add up")
    w("sm_spread:")
    for i, three in enumerate(S.SPREAD):
        w("        DEFB 0x%02X,0x%02X,0x%02X            ; %2d"
          % (three[0], three[1], three[2], i))
    w("")
    w("sm_ini:")
    for r, v in S.INIT:
        w("        DEFB 0x%02X,0x%02X" % (r, v))
    w("")
    path = os.path.join(ROOT, "stormdata.z80s")
    open(path, "w").write("\n".join(o) + "\n")
    print("%s: %d thunder segments, %d rain, %d frames"
          % (path, len(S.TH), len(S.RN), sum(s[0] for s in S.TH)))


if __name__ == "__main__":
    main()
