#!/usr/bin/env python3
"""Compile the tree at each of its eight sizes: tree.z80s.

    python3 tests/mktree.py

The arcade draws its scenery at eight scales and lets an object pop
from one to the next as it comes in, so there are eight sprites here
and not one sprite scaled - which is the only way it could be done
anyway, because scaling a masked sprite on a Z80 costs more than
drawing it.

Each size is one descending walk of SP over its own box, exactly as the
pilot is (mksprite.py does both), so the caller puts SP at the byte
after the bottom right corner and jumps in. What the caller needs to
know about a size - where to jump, and how big the box is - is four
bytes in a table at the foot of the page, and the same widths and
heights go into treeequ.z80s so that the resident code can work out
where the corner is without paging anything in first.

THE TREE IS ALWAYS DRAWN, NEVER CLIPPED. A sprite compiled as a walk of
SP has no idea where the screen ends, so the caller has to know the
whole box fits - which is what makes a tree vanish at the bottom of the
screen rather than sliding off it.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mksprite as S                                    # noqa: E402
import tree as T                                        # noqa: E402

BANK = 0x20 + int(os.environ.get("TREE_FIRST", 24))     # LMPR: RAM over
                                # ROM 0, and the page past the pilot's
WINDOW = 0x7F00                 # what LMPR maps, less the caller's stack


def main(here):
    parts = ["; Generated by tests/mktree.py - do not edit by hand.",
             "; A Space Harrier tree at eight sizes, each one walk of the",
             "; stack pointer from the bottom right corner of its box to",
             "; the top left. The caller puts SP there and jumps in;",
             "; CQ10_RET, from the resident assembly, is the way back.",
             "\n        ORG 0x0000",
             "tree_tab:       ; where to jump, and the box, a size"]
    for h in T.SIZES:
        parts.append("        DEFW tree_%d" % h)
        parts.append("        DEFB %d,%d" % (T.width(h) // 2, h))
    ts, bytes_drawn = [], []
    for h in T.SIZES:
        px, w, _ = T.tree(h)
        rows = T.rows(px)
        out, t = S.walk("tree_%d" % h, rows, w // 2, h, "CQ10_RET")
        parts += out
        ts.append(t)
        bytes_drawn.append(sum(1 for _, kind in rows for k in kind if k))
    parts.append("\n        ASSERT $ <= 0x%04X       ; the window, less the"
                 " caller's stack" % WINDOW)
    open(os.path.join(here, "tree.z80s"), "w").write("\n".join(parts) + "\n")

    equ = ["; Generated by tests/mktree.py - do not edit by hand.",
           "; What the resident code needs to know about the tree's page:",
           "; its bank, where the table is, and the box of each size - the",
           "; last so that SP can be put at the corner before the page the",
           "; sprite lives in is mapped over the board's.",
           "\nTREE_BANK:      EQU 0x%02X      ; LMPR: RAM over ROM 0" % BANK,
           "TREE_TAB:       EQU 0x0000      ; the table, at its foot",
           "TREE_N:         EQU %d           ; sizes" % len(T.SIZES),
           "\ntree_box:       ; bytes wide and scanlines tall, a size"]
    for h in T.SIZES:
        equ.append("        DEFB %d,%d" % (T.width(h) // 2, h))
    open(os.path.join(here, "treeequ.z80s"), "w").write("\n".join(equ) + "\n")

    print("tree.z80s: %d sizes, %d to %d rows, %d to %d T-states,"
          " %d bytes of sprite in all"
          % (len(T.SIZES), T.SIZES[0], T.SIZES[-1], min(ts), max(ts),
             sum(bytes_drawn)))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
