#!/usr/bin/env python3
"""Generate twistdata.z80s: the runs and tables twist.z80s reads.

    python3 tests/mktwistdata.py

Sixty four compiled runs, one per silhouette, and four pages that turn
an angle into which run to jump to and what the two faces are shaded.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import twist as T
from mkchqdata import sam

PUSHOP = {0: 0xE5, 1: 0xC5, 2: 0xD5}    # PUSH HL / PUSH BC / PUSH DE


def defb(v, per=16):
    def one(x):
        return x if isinstance(x, str) else str(x & 0xFF)
    return "\n".join("        DEFB " + ",".join(one(x) for x in v[i:i + per])
                      for i in range(0, len(v), per))


def bg(y):
    """The backdrop's colour on scanline y, for the palette to set.

    The ribbon is drawn in one backdrop index and eight shades, so the
    gradient behind it costs nothing at all - it is two CLUT writes a
    scanline, the same as chequer.z80s.
    """
    t = abs(y - T.H / 2) / (T.H / 2)
    return sam(1 + 2 * (1 - t), 0, 2 + 3 * (1 - t))


def ramp(i):
    """The fourteen shades the faces are drawn in, palette 2 to 15."""
    t = i / 13.0
    return sam(1 + 6 * t, 1 + 4 * t, 5 * t * t)


def main(path):
    runs = []
    for a in range(64):
        runs.append([PUSHOP[s] for s in T.pushes(a)] + [0xC3, 0, 0])
    body = ["\ntw_runs:"]
    for a, r in enumerate(runs):
        body.append("tw_run%d:" % a)
        body.append(defb(r[:-3]))
        body.append("        JP tw_next")
    sh = [[], []]
    for a in range(256):
        _, _, _, sl, sr = T.geom(a)
        sh[0].append(sl * 0x11)
        sh[1].append(sr * 0x11)
    parts = ["; Generated by tests/mktwistdata.py - do not edit by hand.",
             "\nTW_BX:          EQU %d" % T.BX,
             "TW_BW:          EQU %d" % T.BW,
             "\n".join(body),
             "\n        ALIGN 256\ntw_runlo:\n"
             + defb(["(tw_run%d) & 255" % (a & 63) for a in range(256)], 8),
             "\ntw_runhi:\n"
             + defb(["(tw_run%d) >> 8" % (a & 63) for a in range(256)], 8),
             "\ntw_shl:\n" + defb(sh[0]),
             "\ntw_shr:\n" + defb(sh[1]),
             "\ntw_bg:\n" + defb([bg(y) for y in range(T.H)]),
             "\ntw_ramp:\n" + defb([ramp(i) for i in range(14)]),
             "\ntw_shape:\n" + defb(T.SHAPE)]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: 64 runs of %d PUSHes, four pages of tables"
          % (path, 32))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "twistdata.z80s"))
