#!/usr/bin/env python3
"""Generate voxdata.z80s: the map and tables vox.z80s reads.

    python3 tests/mkvoxdata.py

Three pages, all indexed by one byte: the map by (y & 0xF0) | (x & 0x0F),
and the row and colour tables by (h & 0xF0) | z.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vox as V

CAMH = 205


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(path):
    parts = ["; Generated by tests/mkvoxdata.py - do not edit by hand.",
             "\nVX_TOP:         EQU %d" % V.TOP,
             "VX_VH:          EQU %d" % V.VH,
             "VX_COLS:        EQU %d" % V.COLS,
             "VX_STEPS:       EQU %d" % V.STEPS,
             "VX_SKY:         EQU %d" % V.SKY,
             "\n        ALIGN 256\nvx_map:\n" + defb(list(V.mapdata())),
             "\n        ALIGN 256\nvx_row:\n" + defb(list(V.rowtab(CAMH))),
             "\nvx_col:\n" + defb(list(V.coltab()))]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: 16 by 16 map, row and colour a page each, camera at %d"
          % (path, CAMH))


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(os.path.join(here, "voxdata.z80s"))
