#!/usr/bin/env python3
"""Generate the tables wolf3d.z80s reads.

    python3 tests/mkwolfdata.py                 256x144, the default view
    python3 tests/mkwolfdata.py 192x96 96       and a second one alongside

Everything here is data the renderer only reads, so it is generated
rather than built on the Z80. It comes out as two files, because most
of it does not care how big the viewport is:

    wolfdata.z80s     sines, the camera plane, the reciprocals, the
                      map and the textures

    wolfview<tag>.z80s  the viewport's own constants, the height
                      ladder, and the three tables that turn a
                      distance into a wall height and a scaler

so a second viewport size is a second small file and one more harness,
not a second copy of the textures. The view file must be assembled
first: wolf3d.z80s builds on its EQUs.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wolf

MAP = ["################",
       "#..............#",
       "#.####.#####...#",
       "#.#..#.....#.#.#",
       "#.#.##.###.#.#.#",
       "#.#....#...#...#",
       "#.######.#####.#",
       "#........#.....#",
       "#.####.###.###.#",
       "#.#..#.....#...#",
       "#.#.###.####.###",
       "#...#......#...#",
       "###.#.####.###.#",
       "#...#.#......#.#",
       "#.###.#.####...#",
       "################"]


def cells():
    out = []
    for y, row in enumerate(MAP):
        for x, ch in enumerate(row):
            out.append(0 if ch == "." else (1 if (x + y) & 1 else 2))
    return out


def brick(base):
    """Column major, both nibbles the same, so a texel is one byte."""
    t = bytearray(32 * 32)
    for u in range(32):
        for v in range(32):
            r = v // 8
            off = (u + (16 if r & 1 else 0)) % 16
            c = base + 2 if (off < 15 and v % 8 != 7) else base
            t[u * 32 + v] = (c << 4) | c
    return t


def stone(base):
    t = bytearray(32 * 32)
    for u in range(32):
        for v in range(32):
            c = base + 1 if ((u * 7 + v * 13) % 11) < 6 else base + 3
            if (u % 16 == 0) or (v % 16 == 0):
                c = base
            t[u * 32 + v] = (c << 4) | c
    return t


def defw(v, per=8):
    return "\n".join("        DEFW " + ",".join(str(x & 0xFFFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def aligned(parts):
    return "\n".join("\n        ALIGN 256\n%s:\n%s" % (n, b) for n, b in parts)


def write_data(path):
    parts = ["; Generated by tests/mkwolfdata.py - do not edit by hand.",
             aligned((("w3d_sin", defw(wolf.SIN)),
                      ("w3d_plane", defw(wolf.PLANE)),
                      ("w3d_recip", defw(wolf.RECIP)),
                      ("w3d_map", defb(cells())),
                      ("w3d_tex1", defb(list(brick(8)))),
                      ("w3d_tex2", defb(list(stone(1))))))]
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: sin 512, plane 512, recip 512, map 256, textures 2048"
          % path)


def write_view(path, view):
    hidx = [0] * 256
    htop = [0] * 256
    for h in range(wolf.HALFV + 1):
        i, n = wolf.rung(max(1, h))
        hidx[h] = i                                  # which scaler
        htop[h] = wolf.TOPLINE + wolf.HALFV - n // 2  # its top screen row
    head = ("; Generated by tests/mkwolfdata.py %s - do not edit by hand.\n"
            "; Assemble this before wolf3d.z80s: it is the viewport.\n\n"
            "W3D_TOP:        EQU %d\n"
            "W3D_VH:         EQU %d\n"
            "W3D_HALF:       EQU %d\n"
            "W3D_COLS:       EQU %d\n"
            "W3D_XOFF:       EQU %d\n"
            "W3D_NLAD:       EQU %d\n\n"
            "w3d_ladder:\n%s\n"
            % (view, wolf.TOPLINE, wolf.VH, wolf.HALFV, wolf.COLS, wolf.XOFF,
               len(wolf.LADDER), defb(wolf.LADDER)))
    body = aligned((("w3d_hidx", defb(hidx)),
                    ("w3d_htop", defb(htop)),
                    ("w3d_htab", defb(wolf.HTAB))))
    open(path, "w").write(head + body + "\n")
    print("wrote %s: %s, %d ladder rungs, hidx 256, htop 256, htab 1024"
          % (path, view, len(wolf.LADDER)))


def main(argv):
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    view = argv[0] if argv else "256x144"
    tag = argv[1] if len(argv) > 1 else ""
    w, _, h = view.partition("x")
    wolf.set_view(int(w), int(h))
    if not tag:
        write_data(os.path.join(here, "wolfdata.z80s"))
    write_view(os.path.join(here, "wolfview%s.z80s" % tag), view)


if __name__ == "__main__":
    main(sys.argv[1:])
