#!/usr/bin/env python3
"""Generate wolfdata.z80s: the tables and textures wolf3d.z80s reads.

    python3 tests/mkwolfdata.py

Everything here is data the renderer only reads, so it is generated
rather than built on the Z80: sines, the two reciprocal tables, the
map, the textures, and the two tables that put a raw wall height onto
the ladder of heights the scalers were built for.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wolf

MAP = ["################",
       "#..............#",
       "#.####.#####...#",
       "#.#..#.....#.#.#",
       "#.#.##.###.#.#.#",
       "#.#....#...#...#",
       "#.######.#####.#",
       "#........#.....#",
       "#.####.###.###.#",
       "#.#..#.....#...#",
       "#.#.###.####.###",
       "#...#......#...#",
       "###.#.####.###.#",
       "#...#.#......#.#",
       "#.###.#.####...#",
       "################"]


def cells():
    out = []
    for y, row in enumerate(MAP):
        for x, ch in enumerate(row):
            out.append(0 if ch == "." else (1 if (x + y) & 1 else 2))
    return out


def brick(base):
    """Column major, both nibbles the same, so a texel is one byte."""
    t = bytearray(32 * 32)
    for u in range(32):
        for v in range(32):
            r = v // 8
            off = (u + (16 if r & 1 else 0)) % 16
            c = base + 2 if (off < 15 and v % 8 != 7) else base
            t[u * 32 + v] = (c << 4) | c
    return t


def stone(base):
    t = bytearray(32 * 32)
    for u in range(32):
        for v in range(32):
            c = base + 1 if ((u * 7 + v * 13) % 11) < 6 else base + 3
            if (u % 16 == 0) or (v % 16 == 0):
                c = base
            t[u * 32 + v] = (c << 4) | c
    return t


def defw(v, per=8):
    return "\n".join("        DEFW " + ",".join(str(x & 0xFFFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(path):
    hidx = [0] * 256
    htop = [0] * 256
    for h in range(73):
        i, n = wolf.rung(max(1, h))
        hidx[h] = i                                  # which scaler
        htop[h] = wolf.TOPLINE + wolf.HALFV - n // 2  # its top screen row
    parts = ["; Generated by tests/mkwolfdata.py - do not edit by hand."]
    for name, body in (("w3d_sin", defw(wolf.SIN)),
                       ("w3d_plane", defw(wolf.PLANE)),
                       ("w3d_recip", defw(wolf.RECIP)),
                       ("w3d_hidx", defb(hidx)),
                       ("w3d_htop", defb(htop)),
                       ("w3d_map", defb(cells())),
                       ("w3d_tex1", defb(list(brick(8)))),
                       ("w3d_tex2", defb(list(stone(1)))),
                       ("w3d_htab", defb(wolf.HTAB))):
        parts.append("\n        ALIGN 256\n%s:\n%s" % (name, body))
    open(path, "w").write("\n".join(parts) + "\n")
    print("wrote %s: sin 512, recip 512, hidx 256, htop 256, map 256, "
          "textures 2048, htab 1024" % path)


if __name__ == "__main__":
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(sys.argv[1] if len(sys.argv) > 1 else
         os.path.join(here, "wolfdata.z80s"))
