#!/usr/bin/env python3
"""Generate zarchdata.z80s: the tables zarch.z80s reads.

    python3 tests/mkzadata.py

Ten bytes a yaw - the step a cell for each family, and the 24 bit place
its lines radiate from - and four bytes a row of ground, which are the
two colours the chequer alternates at that distance.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import zarch as Z


def defb(v, per=16):
    return "\n".join("        DEFB " + ",".join(str(x & 0xFF)
                                                for x in v[i:i + per])
                     for i in range(0, len(v), per))


def main(here):
    tab = []
    for aA, aB, vA, vB in Z.YAW:
        tab += [aA & 255, aA >> 8, aB & 255, aB >> 8]
        for v in (vA, vB):
            tab += [v & 255, (v >> 8) & 255, (v >> 16) & 255]
    shade = []
    for y in range(Z.TOP, Z.H):
        c = Z.colours(y)
        shade += [c[0] * 0x11, c[0] * 0x11, c[1] * 0x11, c[1] * 0x11]
    parts = ["; Generated by tests/mkzadata.py - do not edit by hand.",
             "\nZA_HZ:          EQU %d          ; the horizon, and the last"
             % Z.HZ,
             "                                ; row of sky",
             "ZA_TOP:         EQU %d         ; the first row of ground" % Z.TOP,
             "ZA_R0:          EQU %d          ; which is this far below the"
             % Z.R0,
             "                                ; horizon",
             "ZA_NYAW:        EQU %d         ; yaws in the table" % Z.NYAW,
             "ZA_SKY:         EQU %d           ; the colours above it" % Z.SKY,
             "ZA_HAZE:        EQU %d" % Z.HAZE,
             "\nza_yawtab:      ; ten bytes a yaw",
             defb(tab, 10),
             "\nza_shade:       ; and four a row: the two colours, doubled",
             defb(shade, 8)]
    open(os.path.join(here, "zarchdata.z80s"), "w").write(
        "\n".join(parts) + "\n")
    print("%d yaws, %d bytes of table; %d rows of ground, %d of shade"
          % (Z.NYAW, len(tab), Z.H - Z.TOP, len(shade)))


if __name__ == "__main__":
    main(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
