#!/usr/bin/env python3
"""Generate crowdata.z80s - the caw, as bytes the SAA1099 wants.

    python3 tests/mkcrowdata.py

Everything here comes out of tests/crow.py, where the caw is written in
Hz and 0-15 amplitudes; this turns the frequencies into the chip's
(511 - n) bytes and writes the tables the routine walks.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import crow as C

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    out = []
    w = out.append
    w(";------------------------------------------------------------------")
    w("; crowdata.z80s - generated by tests/mkcrowdata.py, do not edit")
    w(";")
    w("; The caw: one 50 Hz frame a row, and the three-caw call above it.")
    w(";------------------------------------------------------------------")
    w("")
    w("CROW_FRAMES:    EQU %d           ; 50 Hz frames in one caw" % C.FRAMES)
    w("CROW_CAWS:      EQU %d           ; caws in one call" % C.CAWS)
    w("CROW_GAP:       EQU %d           ; frames of silence between them"
      % C.GAP)
    w("CROW_D1:        EQU %d          ; ch1 sits this far below ch0" % C.D1)
    w("CROW_D2:        EQU %d          ; and ch4 below ch2" % C.D2)
    w("CROW_H4:        EQU %d           ; 4f is this much quieter" % C.H4)
    w("CROW_SEED:      EQU 0x%04X      ; the LFSR that varies each call"
      % C.SEED)
    w("")
    w("; frequency byte, noise clock byte, tone level, noise level")
    w("crow_env:")
    for i, ((n0, n3, ta, na), (f, nc, _, _)) in enumerate(zip(C.ENV, C.CAW)):
        w("        DEFB %3d,%3d,%3d,%3d        ; %2d  %4.0f Hz, rasp %4.0f Hz"
          % (n0, n3, ta, na, i, C.hz(n0, C.OCT), C.hz(n3, C.NOCT)))
    w("")
    w("; a call: how far up, and how much quieter, each caw of it is")
    w("crow_seq:")
    for t, d in C.SEQ:
        w("        DEFB %3d,%3d" % (t, d))
    w("")
    w("; what crow_init sends: register, value")
    w("CROW_INITS:     EQU %d" % len(C.INIT))
    w("crow_ini:")
    for r, v in C.INIT:
        w("        DEFB 0x%02X,0x%02X" % (r, v))
    w("")
    path = os.path.join(ROOT, "crowdata.z80s")
    open(path, "w").write("\n".join(out) + "\n")
    print("%s: %d frames, %d caws, %d init writes"
          % (path, C.FRAMES, C.CAWS, len(C.INIT)))


if __name__ == "__main__":
    main()
