#!/usr/bin/env python3
"""Generate stringsdata.z80s - the pad's chords and tables.

    python3 tests/mkstringsdata.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import strings as T

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    o = []
    w = o.append
    w(";------------------------------------------------------------------")
    w("; stringsdata.z80s - generated by tests/mkstringsdata.py, do not edit")
    w(";------------------------------------------------------------------")
    w("")
    w("ST_CHORDS:      EQU %d           ; chords in the progression"
      % len(T.CHORD))
    w("ST_TOTAL:       EQU %d         ; frames the whole thing lasts" % T.TOTAL)
    w("ST_DET:         EQU %d           ; the second copy, in frequency units"
      % T.DET)
    w("ST_VIBLEN:      EQU %d          ; frames a vibrato cycle" % T.VIB_LEN)
    w("ST_SPREAD:      EQU %d           ; how far apart the notes' phases are"
      % T.VIB_SPREAD)
    w("ST_ATTLEN:      EQU %d          ; frames of attack" % len(T.ATT))
    w("ST_RELLEN:      EQU %d          ; and of release" % len(T.REL))
    w("ST_SUS:         EQU %d          ; the level in between" % T.SUS)
    w("ST_INITS:       EQU %d          ; registers st_init sets up" % len(T.INIT))
    w("")
    w("; each chord: three (frequency byte, octave register byte), then how")
    w("; many frames it holds. Both channels of a pair share an octave, so")
    w("; the octave byte is just the octave in both nibbles.")
    w("st_chords:")
    for (notes, dur), (names, _) in zip(T.CHORD, T.CHORDS):
        w("        DEFB " + ",".join("%3d,0x%02X" % (n, ob) for n, ob in notes)
          + ",%3d   ; %-12s %5.2f s"
          % (dur, "-".join(names), dur / 50.0))
    w("")
    w("; one vibrato cycle, laid down twice so +%d never runs off the end"
      % (2 * T.VIB_SPREAD))
    w("st_vib:")
    w("        DEFB " + ",".join("%3d" % (v & 0xFF) for v in T.VIB[:12]))
    w("        DEFB " + ",".join("%3d" % (v & 0xFF) for v in T.VIB[12:]))
    w("")
    w("st_att:")
    w("        DEFB " + ",".join("%2d" % v for v in T.ATT))
    w("st_rel:")
    for i in range(0, len(T.REL), 15):
        w("        DEFB " + ",".join("%2d" % v for v in T.REL[i:i + 15]))
    w("")
    w("st_ini:")
    for r, v in T.INIT:
        w("        DEFB 0x%02X,0x%02X" % (r, v))
    w("")
    path = os.path.join(ROOT, "stringsdata.z80s")
    open(path, "w").write("\n".join(o) + "\n")
    print("%s: %d chords, %d frames" % (path, len(T.CHORD), T.TOTAL))


if __name__ == "__main__":
    main()
