"""CLI-level tests: files land on disk, the table adds up, output re-parses."""

import json

import pytest

from codesprite.cli import lower_bound, main
from codesprite.sprite import Sprite


SHIP = """\
..ff..
.f11f.
f1991f
.f11f.
"""


@pytest.fixture()
def ship(tmp_path):
    path = tmp_path / "ship.txt"
    path.write_text(SHIP)
    return path


def test_compile_writes_one_file_per_variant(ship, tmp_path, capsys):
    out = tmp_path / "out"
    assert main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)]) == 0
    files = sorted(p.name for p in out.glob("*.z80s"))
    assert files == [
        "spr_draw_single_xe.z80s",
        "spr_draw_single_xo.z80s",
        "spr_manifest.z80s",
    ]
    table = capsys.readouterr().out
    assert "spr_draw_single_xe" in table
    assert "file(s)" in table


def test_x_align_2_generates_one_phase(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out), "--x-align", "2"])
    assert sorted(p.name for p in out.glob("*_draw_*.z80s")) == ["spr_draw_single_xe.z80s"]


def test_stats_json_matches_the_files(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)])
    data = json.loads((out / "spr_stats.json").read_text())
    assert data["name"] == "spr"
    assert len(data["variants"]) == 2
    for variant in data["variants"]:
        text = (out / f"{variant['variant']}.z80s").read_text()
        assert f"{variant['variant']}_tstates  EQU {variant['tstates']}" in text
        assert f"EQU {variant['size']}" in text
        assert variant["size"] > 0 and variant["tstates"] > 0
    assert data["total_size"] == sum(v["size"] for v in data["variants"])


def test_sizes_command_reprints_the_table(ship, tmp_path, capsys):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)])
    capsys.readouterr()
    assert main(["sizes", str(out)]) == 0
    assert "spr_draw_single_xe" in capsys.readouterr().out


def test_emitted_source_has_a_ret_and_metadata(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)])
    text = (out / "spr_draw_single_xe.z80s").read_text()
    assert text.rstrip().endswith("EQU 0") or "_patches  EQU" in text
    assert "spr_draw_single_xe:" in text
    assert "RET" in text
    assert "Generated by codesprite" in text


def test_inspect_reports_both_phases(ship, capsys):
    assert main(["inspect", str(ship)]) == 0
    output = capsys.readouterr().out
    assert "phase 0" in output and "phase 1" in output


def test_unimplemented_options_fail_loudly(ship, tmp_path):
    out = tmp_path / "out"
    for extra in (
        ["--routines", "erase"],
        ["--form", "list"],
        ["--reloc", "patch"],
    ):
        with pytest.raises(SystemExit):
            main(["compile", str(ship), "--name", "s", "--out-dir", str(out)] + extra)


def test_verification_runs_by_default(ship, tmp_path, monkeypatch):
    """The compile path must verify; prove it by making verification fail."""
    import codesprite.cli as cli

    calls = []

    def fake_verify(*args, **kwargs):
        calls.append(args)
        return None

    monkeypatch.setattr(cli, "verify_draw", fake_verify)
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(tmp_path / "o")])
    assert len(calls) == 2  # one per phase


def test_lower_bound_is_below_generated_cost(ship, tmp_path):
    sprite = Sprite([[1] * 8 for _ in range(8)])
    packed = sprite.pack(0)
    assert 0 < lower_bound(packed) <= 8 * 8 // 2 * 11


def test_trim_shrinks_the_sprite(tmp_path, capsys):
    path = tmp_path / "pad.txt"
    path.write_text("....\n.11.\n....\n")
    main(["inspect", str(path), "--trim"])
    assert "2x1 pixels" in capsys.readouterr().out
