"""CLI-level tests: files land on disk, the table adds up, output re-parses."""

import json

import pytest

from codesprite.cli import lower_bound, main
from codesprite.sprite import Sprite


SHIP = """\
..ff..
.f11f.
f1991f
.f11f.
"""


@pytest.fixture()
def ship(tmp_path):
    path = tmp_path / "ship.txt"
    path.write_text(SHIP)
    return path


def test_compile_writes_one_file_per_variant(ship, tmp_path, capsys):
    out = tmp_path / "out"
    assert main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)]) == 0
    files = sorted(p.name for p in out.glob("*.z80s"))
    assert files == [
        "spr_draw_single_xe.z80s",
        "spr_draw_single_xo.z80s",
        "spr_manifest.z80s",
    ]
    table = capsys.readouterr().out
    assert "spr_draw_single_xe" in table
    assert "file(s)" in table


def test_x_align_2_generates_one_phase(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out), "--x-align", "2"])
    assert sorted(p.name for p in out.glob("*_draw_*.z80s")) == ["spr_draw_single_xe.z80s"]


def test_stats_json_matches_the_files(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)])
    data = json.loads((out / "spr_stats.json").read_text())
    assert data["name"] == "spr"
    assert len(data["variants"]) == 2
    for variant in data["variants"]:
        text = (out / f"{variant['variant']}.z80s").read_text()
        assert f"{variant['variant']}_tstates  EQU {variant['tstates']}" in text
        assert f"EQU {variant['size']}" in text
        assert variant["size"] > 0 and variant["tstates"] > 0
    assert data["total_size"] == sum(v["size"] for v in data["variants"])


def test_sizes_command_reprints_the_table(ship, tmp_path, capsys):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)])
    capsys.readouterr()
    assert main(["sizes", str(out)]) == 0
    assert "spr_draw_single_xe" in capsys.readouterr().out


def test_emitted_source_has_a_ret_and_metadata(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out)])
    text = (out / "spr_draw_single_xe.z80s").read_text()
    assert text.rstrip().endswith("EQU 0") or "_patches  EQU" in text
    assert "spr_draw_single_xe:" in text
    assert "RET" in text
    assert "Generated by codesprite" in text


def test_inspect_reports_both_phases(ship, capsys):
    assert main(["inspect", str(ship)]) == 0
    output = capsys.readouterr().out
    assert "phase 0" in output and "phase 1" in output


def test_unimplemented_options_fail_loudly(ship, tmp_path):
    out = tmp_path / "out"
    for extra in (
        ["--routines", "nonsense"],
        ["--form", "list"],  # needs --reloc register
        ["--routines", "restore_bb"],  # needs --backbuffer-base
        ["--clip", "y-spill"],
    ):
        with pytest.raises(SystemExit):
            main(["compile", str(ship), "--name", "s", "--out-dir", str(out)] + extra)


@pytest.mark.parametrize("reloc", ["none", "patch", "register"])
def test_every_relocation_mode_compiles_and_verifies(ship, tmp_path, reloc):
    """Compilation verifies by running the code, so reaching the table is
    itself the assertion that the generated routines are correct."""
    out = tmp_path / reloc
    assert main(
        ["compile", str(ship), "--name", "spr", "--out-dir", str(out),
         "--reloc", reloc]
    ) == 0
    files = sorted(p.name for p in out.glob("spr_draw_*.z80s"))
    # Fixed builds have one file per x phase; relocatable ones also split by
    # y parity, because the row-step encoding depends on it.
    expected = 2 if reloc == "none" else 4
    assert len(files) == expected, files


def test_patched_variant_emits_a_setpos_routine(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out),
          "--reloc", "patch"])
    text = (out / "spr_draw_single_xe_ye.z80s").read_text()
    assert "spr_draw_single_xe_ye_setpos:" in text
    assert "LD A,C" in text or "LD A,D" in text
    assert ".p0:" in text
    assert "C = (y&1)*128 + x/2" in text  # the entry contract is documented


def test_register_variant_documents_its_hl_contract(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out),
          "--reloc", "register"])
    text = (out / "spr_draw_single_xe_ye.z80s").read_text()
    assert "HL = address of the sprite's top-left screen byte" in text
    assert "LD HL,$" not in text  # no absolute addresses in register mode


def test_y_align_2_halves_the_variant_count(ship, tmp_path):
    out = tmp_path / "out"
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(out),
          "--reloc", "patch", "--y-align", "2"])
    assert len(list(out.glob("spr_draw_*.z80s"))) == 2


def test_mode_switch_changes_the_generated_code(tmp_path):
    path = tmp_path / "solid.txt"
    path.write_text("\n".join("7" * 16 for _ in range(8)) + "\n")
    sizes = {}
    for mode in ("hl", "stack", "best"):
        out = tmp_path / mode
        main(["compile", str(path), "--name", "s", "--out-dir", str(out),
              "--mode", mode, "--x-align", "2"])
        sizes[mode] = json.loads((out / "s_stats.json").read_text())["variants"][0]
    assert sizes["stack"]["tstates"] < sizes["hl"]["tstates"]
    assert sizes["best"]["tstates"] <= sizes["stack"]["tstates"]


def test_verification_runs_by_default(ship, tmp_path, monkeypatch):
    """The compile path must verify; prove it by making verification fail."""
    import codesprite.cli as cli

    calls = []

    def fake_verify(*args, **kwargs):
        calls.append(args)
        return None

    monkeypatch.setattr(cli, "verify_draw", fake_verify)
    main(["compile", str(ship), "--name", "spr", "--out-dir", str(tmp_path / "o")])
    assert len(calls) == 2  # one per phase


def test_lower_bound_is_below_generated_cost(ship, tmp_path):
    sprite = Sprite([[1] * 8 for _ in range(8)])
    packed = sprite.pack(0)
    assert 0 < lower_bound(packed) <= 8 * 8 // 2 * 11


def test_trim_shrinks_the_sprite(tmp_path, capsys):
    path = tmp_path / "pad.txt"
    path.write_text("....\n.11.\n....\n")
    main(["inspect", str(path), "--trim"])
    assert "2x1 pixels" in capsys.readouterr().out


def test_stack_use_is_documented_in_every_output(tmp_path):
    """A caller must be able to tell, without reading the code, whether a
    routine needs interrupts off."""
    path = tmp_path / "solid.txt"
    path.write_text("\n".join("7" * 16 for _ in range(8)) + "\n")
    out = tmp_path / "out"
    main(["compile", str(path), "--name", "s", "--out-dir", str(out),
          "--x-align", "2"])

    text = (out / "s_draw_single_xe.z80s").read_text()
    assert "WRITES THROUGH SP" in text
    assert "s_draw_single_xe_uses_stack EQU 1" in text
    assert "the CALLER must have done DI already" in text

    data = json.loads((out / "s_stats.json").read_text())
    assert data["variants"][0]["uses_stack"] is True
    assert "| yes |" in (out / "s_SIZES.md").read_text()
    assert "interrupts must be off" in (out / "s_manifest.z80s").read_text()


def test_stack_free_build_says_so_and_uses_no_sp(tmp_path):
    path = tmp_path / "solid.txt"
    path.write_text("\n".join("7" * 16 for _ in range(8)) + "\n")
    out = tmp_path / "out"
    main(["compile", str(path), "--name", "s", "--out-dir", str(out),
          "--x-align", "2", "--stack", "none"])

    text = (out / "s_draw_single_xe.z80s").read_text()
    assert "does not touch SP; safe with interrupts enabled" in text
    assert "s_draw_single_xe_uses_stack EQU 0" in text
    for forbidden in ("PUSH ", "POP ", "LD SP,"):
        assert forbidden not in text, forbidden
    assert json.loads((out / "s_stats.json").read_text())["variants"][0][
        "uses_stack"
    ] is False


def test_routine_can_be_asked_to_guard_interrupts_itself(tmp_path):
    path = tmp_path / "solid.txt"
    path.write_text("\n".join("7" * 16 for _ in range(4)) + "\n")
    out = tmp_path / "out"
    main(["compile", str(path), "--name", "s", "--out-dir", str(out),
          "--x-align", "2", "--interrupts", "di"])
    text = (out / "s_draw_single_xe.z80s").read_text()
    assert "this routine disables them itself" in text
    assert "\n                DI" in text


def test_stack_none_costs_more_but_still_draws(tmp_path):
    path = tmp_path / "solid.txt"
    path.write_text("\n".join("7" * 16 for _ in range(8)) + "\n")
    costs = {}
    for policy in ("allow", "none"):
        out = tmp_path / policy
        main(["compile", str(path), "--name", "s", "--out-dir", str(out),
              "--x-align", "2", "--stack", policy])
        costs[policy] = json.loads((out / "s_stats.json").read_text())["variants"][0]
    assert costs["allow"]["tstates"] < costs["none"]["tstates"]


def test_contradictory_stack_options_are_refused(tmp_path):
    path = tmp_path / "s.txt"
    path.write_text("77\n")
    with pytest.raises(SystemExit):
        main(["compile", str(path), "--name", "s", "--out-dir", str(tmp_path / "o"),
              "--stack", "none", "--mode", "stack"])
